<?php
$week_end = time() - (60 * 60 * 24 * 7);
$week_start = time() - (60 * 60 * 24 * 14);
$week_users = $db->where('lastseen',$week_start,'>=')->where('lastseen',$week_end,'<=')->getValue(T_USERS,'COUNT(*)');

$month_end = time() - (60 * 60 * 24 * 30);
$month_start = time() - (60 * 60 * 24 * 60);
$month_users = $db->where('lastseen',$month_start,'>=')->where('lastseen',$month_end,'<=')->getValue(T_USERS,'COUNT(*)');

$month_end3 = time() - (60 * 60 * 24 * 61);
$month_start3 = time() - (60 * 60 * 24 * 150);
$month_users3 = $db->where('lastseen',$month_start3,'>=')->where('lastseen',$month_end3,'<=')->getValue(T_USERS,'COUNT(*)');

$month_end6 = time() - (60 * 60 * 24 * 151);
$month_start6 = time() - (60 * 60 * 24 * 210);
$month_users6 = $db->where('lastseen',$month_start6,'>=')->where('lastseen',$month_end6,'<=')->getValue(T_USERS,'COUNT(*)');

$month_end9 = time() - (60 * 60 * 24 * 211);
$month_start9 = time() - (60 * 60 * 24 * 300);
$month_users9 = $db->where('lastseen',$month_start9,'>=')->where('lastseen',$month_end9,'<=')->getValue(T_USERS,'COUNT(*)');

$year_end = time() - (60 * 60 * 24 * 365);
$year_users = $db->where('lastseen',$year_end,'<=')->getValue(T_USERS,'COUNT(*)');
?>
<div class="container-fluid">
    <div>
        <h3>Gửi E-mail</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Công cụ</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Gửi E-mail</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                  <h6 class="card-title">Gửi E-mail đến người dùng</h6>
                    <div id="alert"></div>
                    <form class="mailing-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">Chủ đề</label>
                                <input type="text" id="subject" name="subject" class="form-control">
                                <small class="admin-info">Chọn tiêu đề cho tin nhắn của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">Tin nhắn (HTML được cho phép)</label>
                                <textarea name="message" id="message" class="form-control" cols="30" rows="10"></textarea>
                                <small class="admin-info">Viết tin nhắn của bạn ở đây.</small>
                            </div>
                        </div>
                        <label for="send_to">Gửi E-mail đến</label>
                        <select class="form-control show-tick" id="send_to" name="send_to">
                            <option value="all">Tất cả người dùng</option>
                            <option value="active">Tất cả người dùng hoạt động</option>
                            <option value="inactive">Tất cả người dùng không hoạt động</option>
                            <option value="week">Người dùng không đăng nhập khoảng 1 tuần (<?php echo $week_users; ?> Người dùng)</option>
                            <option value="month">Người dùng không đăng nhập khoảng 1 tháng (<?php echo $month_users; ?> Người dùng)</option>
                            <option value="3month">Người dùng không đăng nhập khoảng 3 tháng (<?php echo $month_users3; ?> Người dùng)</option>
                            <option value="6month">Người dùng không đăng nhập khoảng 6 tháng (<?php echo $month_users6; ?> Người dùng)</option>
                            <option value="9month">Người dùng không đăng nhập khoảng 9 tháng (<?php echo $month_users9; ?> Người dùng)</option>
                            <option value="year">Người dùng không đăng nhập khoảng 1 năm (<?php echo $year_users; ?> Người dùng)</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <div class="form-group form-float selected_users_div" style="display:none;">
                            <div class="form-line">
                                <label class="form-label" id="mailing-selected-users">Selected Users</label>
                                <input value="" data-role="tagsinput sometext" id="selected_users" name="selected_emails" readonly>
                            </div>
                        </div>
                        <small class="admin-info">Chọn thể loại người dùng muốn gửi tin nhắn đến.</small>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label" id="mailing-selected-users">Tìm kiếm người dùng (Optional) <span></span></label>
                                <input type="text" class="form-control" oninput="Wo_SearchMailingUsers(this.value)" autocomplete="off">
                                <small class="admin-info">Chỉ gửi cho người dùng đó, để trống để gửi cho tất cả người dùng.</small>
                            </div>
                        </div>
                        <div class="search-mailing-users hidden"></div>
                        <div class="form-group">
                          <label for="test_message">Kiểm tra tin nhắn (Gửi đầu tiên đến E-mail của bạn)</label>
                           <input type="checkbox" id="test_message" class="filled-in" name="test_message">
			            </div>
                        
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <input type="hidden" name="selected_emails" id="selected_emails"> -->
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Gửi</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
var mailing_users = [];
$(function () {
    let users = $("#selected_users").tagsinput({
      maxTags: 1500,
      itemValue: 'id',
      itemText: 'text',
      allowDuplicates: false,
    });
    $("#selected_users").on('itemRemoved', function(event) {
        var tag = event.item;
        var items = mailing_users.filter(id => {
            return id != tag.id;
        });
        setTimeout(function () {
            mailing_users = items;
            $("#mailing-selected-users span").text(mailing_users.length);
        },100);
        
    });
   $('form.mailing-settings').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=send_mail_to_mock_users',
      beforeSend: function () {
         $('form.mailing-settings').find('.waves-effect').text('Please wait..');
      },
      success: function (data) {
         if (data.status == 400) {
            $("#alert").html('<div class="alert alert-danger">'+ data['message'] +'</div>');
         } else if (data.status == 200) {
            $("#alert").html('<div class="alert alert-success">Message Sent!</div>');
         } else if (data.status == 300) {
            $("#alert").html('<div class="alert alert-success">Messages are being sent in background.</div>');
         }
         $('form.mailing-settings').find('.waves-effect').text('Send');
      }
   });

   $(document).on('click', '.search-mailing-users p', function(event) {
      event.preventDefault();
      var id = $(this).attr('data-user');
      if ($.inArray(id, mailing_users) == -1) {
         mailing_users.push(id);
         $('.selected_users_div').slideDown();
         $("#selected_users").tagsinput('add', { id: id, text: $(this).text() });
         $("#mailing-selected-users span").text(mailing_users.length);
         $("#selected_emails").val(mailing_users.join());
         $(this).remove();
      }

   });

});
function Wo_SearchMailingUsers(name = ''){
   if (!name) { 
        $('.search-mailing-users').removeClass('hidden').html('');
        return false;
    }
   $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'admin_setting',s:'get_users_emails',name:name},
   })
   .done(function(data) {
      if (data.status == 200) {
         $('.search-mailing-users').removeClass('hidden').html(data.html);     
      }
      else{
        $('.search-mailing-users').removeClass('hidden').html('');  
      }
   })
   .fail(function() {
      console.log("error");
   })
}
</script>