<div class="container-fluid">
    <div>
        <h3>Cập nhật và sửa lỗi</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Cập nhật</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Cập nhật và sửa lỗi</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Kiểm tra cập nhật mới</h6>
                    <div class="CheckForUpdates_alert"></div>
                    <div class="alert alert-warning">
                        Hệ thống tự động cập nhật hiện đang bị vô hiệu hóa do nhiều chủ để, nếu bạn muốn cập nhật trang, bạn có thể cập nhật trang của mình theo <a href="https://docs.wowonder.com/faqs.html#a-23423422">hướng dẫn này</a>
                    </div>
                	<!-- <div class="alert alert-danger">
                		<b>Important:</b> <br><br>

                		<b>1.</b> If you have edited the themes name, this system won't update your site.<br><br>
                		<b>2.</b> If you are using wonderful, the theme folder should be reset to "wonderful".<br><br>
                		<b>3.</b> If you are using wowonder, the theme folder should be reset to "wowonder".
                	</div>
                    <div class="alert alert-success email-settings-alert"></div>
                    <form class="email-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="purchase_code" name="purchase_code" class="purchase_code form-control">
                                <label class="form-label">Purchase Code</label>
                            </div>
                        </div>
                        <span class="help-block">Your WoWonder purchase code, your purchase code won't be saved for security reasons.</span>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <input type="hidden" value="<?php echo $wo['script_version']?>" id="script-version">
                        <button type="button" class="btn btn-primary m-t-15 waves-effect check-update-button" onclick="Wo_CheckForUpdates()">Check For Updates</button>
                    </form>
                </div> -->
            </div>
        </div>
         <div class="col-lg-6 col-md-6">
            <div class="card updates-layout hidden">
                <div class="card-body">
                    <h6 class="card-title">Cập nhật mới là khả dụng!</h6>
                    <div class="RunUpdates_alert"></div>
                    <div>Các phiên bản sau sẽ được cài đặt:</div>
                    <div class="updates"></div>
                    <button class="btn btn-success waves-effect waves-light m-t-10 run-update" onclick="Wo_RunUpdates()">Cập nhật cài đặt</button>
                    <button class="btn btn-success waves-effect waves-light m-t-10 download-update" onclick="Wo_DownloadUpdates()">Cập nhật tải xuống</button>
                    <br><br>
                    <div>
                    	1. Nút "Cập nhật cài đặt" sẽ tải xuống và tự động cập nhật lên trang web của bạn phiên bản mới nhất. <span class="help-block red" style="color: red">Ghi chú: "Cập nhật cài đặt" sẽ thay thế và ghi đè tất cả các mã sửa đổi của bạn, nếu bạn muốn giữ mã sửa đổi, vui lòng sử dụng quy trình thủ công (nút tải xuống).<br>Chắc chắn tạo bản sao lưu trước khi bắt đầu quá trình cập nhật.</span><br>
                    </div>
                     <div>
                    	2. Nút "Cập nhật tải xuống" sẽ tải xuống phiên bản mới nhất và lưu chúng ở đĩa máy chủ, bạn có thể tìm chúng trong thư mục "/updates". Bạn có thể cập nhật trang của bạn thủ công theo hướng dẫn trong cập nhật.
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

function Wo_CheckForUpdates() {
	var purchase_code = $('.purchase_code').val();
	var script_version = $('#script-version').val();
	$('.check-update-button').text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f: 'check_for_updates', purchase_code: purchase_code}, function (data) {
		if (data.status == 200) {
			$('.updates-layout').removeClass('hidden');
			$('.updates').html('<ul class="list-group"></ul>').find('ul').append('<li class="list-group-item hidden">Versions</li>');;
			data.versions.forEach(function(entry) {
			    $('.updates').find('ul').append('<li class="list-group-item"> ' + entry + '</li>');
			});
			$('#script-version').val(data.script_version);
		} else if (data.status == 300) {
            $('.CheckForUpdates_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Your site is up to date.</div>');
            setTimeout(function () {
                $('.CheckForUpdates_alert').empty();
            }, 2000);
		} else if (data.status == 400) {
            $('.CheckForUpdates_alert').html('<div class="alert alert-danger">'+data.ERROR_NAME+'</div>');
            setTimeout(function () {
                $('.CheckForUpdates_alert').empty();
            }, 2000);
		}  else  {
            $('.CheckForUpdates_alert').html('<div class="alert alert-danger">Error while connecting to server, please check your details</div>');
            setTimeout(function () {
                $('.CheckForUpdates_alert').empty();
            }, 2000);
		}
		$('.check-update-button').text('Check For Updates');
	});
}
function Wo_DownloadUpdates() {
	$('.download-update').text('Downloading, Please wait..');
	var purchase_code = $('.purchase_code').val();
	$.get(Wo_Ajax_Requests_File(), {f: 'download_updates', purchase_code: purchase_code}, function (data) {
		if (data.status == 200) {
            $('.RunUpdates_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> The update(s) was downloaded.</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
			$('.updates-layout').addClass('hidden');
		} else if (data.status == 300) {
            $('.RunUpdates_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Your site is up to date.</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		} else if (data.status == 400) {
            $('.RunUpdates_alert').html('<div class="alert alert-danger">'+data.ERROR_NAME+'</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		}  else  {
            $('.RunUpdates_alert').html('<div class="alert alert-danger">Error while connecting to server, please check your details</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		}
		$('.download-update').text('Download Updates');
	});
}

function Wo_RunUpdates() {
	$('.run-update').text('Updating, Please wait..');
	var purchase_code = $('.purchase_code').val();
	var script_version = $('#script-version').val();
	$.get('<?php echo $wo['config']['site_url']?>/updater.php', {f: 'run_updater', purchase_code: purchase_code, script_version:script_version}, function (data) {
		if (data.status == 200) {
            $('.RunUpdates_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Your site was updated, please refresh your page and clean your browser cache.</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
			$('.updates-layout').addClass('hidden');
		} else if (data.status == 300) {
            $('.RunUpdates_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Your site is up to date.</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		} else if (data.status == 400) {
            $('.RunUpdates_alert').html('<div class="alert alert-danger">'+data.ERROR_NAME+'</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		}  else  {
            $('.RunUpdates_alert').html('<div class="alert alert-danger">Error while connecting to server, please check your details</div>');
            setTimeout(function () {
                $('.RunUpdates_alert').empty();
            }, 2000);
		}
		$('.run-update').text('Install Updates');
	});
}
</script>