<div class="container-fluid">
    <div>
        <h3>Danh sách thay đổi</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Danh sách thay đổi</li>
            </ol>
        </nav>
    </div>
		<div class="alert alert-info">Các bản cập nhật được cung cấp miễn phí trọn đời nếu bạn sở hữu mã mua hợp lệ, bạn có muốn?<a href="https://bit.ly/2R2jrcz" target="_blank">Nhận mã mua hàng hợp lệ!</a></div>
            <!-- Changelogs -->
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                      <h6 class="card-title">v4.2.1 <small>Ngày 17 tháng 05 năm 2023 </small> </h6>
                          <ul>
                             <li> [Đã sửa] trang liên hệ với chúng tôi về chủ đề sunshien.</li>
                             <li> [Đã sửa] danh sách tin nhắn không hiển thị trên điện thoại.</li>
                             <li> [Đã sửa] tắt/bật thông báo về chủ đề thời tiết.</li>
                             <li> [Đã sửa] chuông thông báo không hiển thị vào ngày trên trang hồ sơ.</li>
                             <li> [Đã sửa] văn bản thông báo không hiển thị trên chủ đề thời tiết.</li>
                             <li> [Đã sửa] không thể thực hiện nhận xét trên bài viết. </li>
                             <li> [Đã sửa] Người kiểm duyệt không thể xác minh người dùng.</li>
                             <li> [Đã sửa] không thể thay đổi hình đại diện trong trang quản lý giới tính trong bảng quản trị.</li>
                             <li> [Đã sửa] sắp xếp theo giá không hoạt động tốt trên thị trường.</li>
                             <li> [Đã sửa] tạo bài viết trên nhật ký và đăng lên nhật ký không hiện các từ có dấu.</li>
                             <li> [Đã sửa] hơn 10 lỗi nhỏ ở mặt sau và mặt trước.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                      <h6 class="card-title">v4.2 <small> Ngày 02 tháng 05 năm 2023 </small> </h6>
                          <ul>
                               <li> [Đã bổ sung] chủ đề mới, cập nhật chủ đề lên v2 hoàn toàn.</li>
                               <li> [Đã bổ sung] hệ thống tạo hình ảnh AI, giờ đây người dùng có thể tạo hình ảnh trực tiếp và đăng lên.</li>
                               <li> [Đã thêm] hệ thống tạo văn bản và bài đăng AI, giờ đây người dùng có thể tạo văn bản và đăng ý tưởng trực tiếp rồi đăng chúng.</li>
                               <li> [Đã thêm] hệ thống tạo bài viết AI, giờ đây người dùng có thể tạo bài viết trong hệ thống nhật ký.</li>
                               <li> [Đã bổ sung] hệ thống chỉnh sửa hình ảnh AI, người dùng có thể chỉnh sửa ảnh đại diện và ảnh bìa theo ý muốn bằng cách sử dụng văn bản quảng cáo.</li>
                               <li> [Đã thêm] hệ thống AI sử dụng hệ thống tín dụng, tính phí người dùng trang web của bạn cho mỗi hình ảnh, văn bản được tạo.</li>
                               <li> [Đã bổ sung] xác thực google cho hai hệ thống xác thực.</li>
                               <li> [Đã bổ sung] xác thực cho hai hệ thống xác thực.</li>
                               <li> [Đã thêm] cổng thanh toán Braintree.</li>
                               <li> [Đã bổ sung] API mới.</li>
                               <li> [Đã thêm] hạn chế tên người dùng, không cho phép và loại tên người dùng.</li>
                               <li> [Đã thêm] tùy chọn chất lượng ảnh trong bảng quản trị.</li>
                               <li> [Đã bổ sung] khả năng bật hoặc tắt trang khởi động. </li>
                               <li> [Đã bổ sung] khả năng chọn ngôn ngữ RTL từ bảng quản trị.</li>
                               <li> [Đã bổ sung] hỗ trợ cho PHP v8.2</li>
                               <li> [Đã cập nhật] trình soạn thảo văn bản.</li>
                               <li> [Đã sửa] hơn 10 vấn đề về API.</li>
                               <li> [Đã sửa] hệ thống sơ đồ trang web tạo ra hơn 50K phần tử trong một tệp.</li>
                               <li> [Đã sửa] thanh toán Yoomoney không cấp vốn.</li>
                               <li> [Đã sửa] trình soạn thảo văn bản không thể thêm hình ảnh trong điều khoản chỉnh sửa hoặc chỉnh sửa trang trong bảng quản trị.</li>
                               <li> [Đã sửa] bộ lọc theo người dùng đang hoạt động trong Quản trị > Quản lý người dùng không hoạt động.</li>
                               <li> [Đã sửa] người kiểm duyệt không thể chỉnh sửa ngôn ngữ.</li>
                               <li> [Đã sửa] tắt hệ thống nhật ký vẫn hiển thị liên kết tạo bài viết trong tiêu đề.</li>
                               <li> [Đã sửa lỗi] API Google Vision không hoạt động nếu đăng album.</li>
                               <li> [Đã sửa] video không tự động tạm dừng nếu bạn cuộn xuống các bài đăng khác. </li>
                               <li> [Đã sửa] bài đăng của người dùng bị cấm vẫn hiển thị trên trang hashtag.</li>
                               <li> [Đã sửa] nếu hashtag có chữ in hoa thì nó sẽ trở thành một hashtag hoàn toàn khác.</li>
                               <li> [Đã sửa] công cụ chọn ngày bị lỗi trong trang cài đặt.</li>
                               <li> [Đã sửa] không thể tạo mã lời mời trong bảng quản trị.</li>
                               <li> [Đã sửa] URL/phim/xem trả về trang 404.</li>
                               <li> [Đã sửa] khi bạn tạo người dùng giả mạo và đăng nhập bằng thông tin người dùng giả mạo, bạn sẽ chuyển đến lỗi 404 và không thể đăng nhập</li>
                               <li> [Đã sửa] không thể tải lên hình ảnh SVG từ phần chỉnh sửa hoặc thêm phản ứng từ bảng quản trị.</li>
                               <li> [Đã sửa] lệnh gọi API openweathermap, giờ đây tất cả đã được thanh toán.</li>
                               <li> [Đã sửa] cấp độ thành viên chuyên nghiệp vẫn hiển thị tên cũ trên trang tổng quan ngay cả sau khi thay đổi tất cả tên.</li>
                               <li> [Đã sửa] ReCAPTCHA không hiển thị trong lần truy cập đầu tiên vào trang liên hệ với chúng tôi, nếu bạn làm mới trang thì nó sẽ hiển thị sau đó.</li>
                               <li> [Đã sửa] Google dịch không hoạt động.</li>
                               <li> [Đã sửa] âm thanh thông báo không hoạt động với Ajax. </li>
                               <li> [Đã sửa] không thể đăng xuất bằng nginx.</li>
                               <li> [Đã sửa] tất cả email đang được gửi ở định dạng mime.</li>
                               <li> [Đã sửa] các sự kiện đã kết thúc, không nên mở để tham gia.</li>
                               <li> [Đã sửa] nếu bạn muốn đặt người dùng làm quản trị viên cho trang của mình, không thể thay đổi đặc quyền cho người dùng đó. Nút này không hoạt động</li>
                               <li> [Đã sửa] 1 vấn đề bảo mật.</li>
                               <li> [Đã sửa] hơn 20 lỗi nhỏ khác.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                      <h6 class="card-title">v4.1.5 <small> Ngày 14 tháng 02 năm 2023 <span style="color:red">[Cập nhật khẩn cấp]</span></small> </h6>
                          <ul>
                               <li> [Đã thêm] hệ thống bộ đệm, giờ đây tốc độ trang web của bạn nhanh hơn 80%, tải trung bình giảm từ 1,2 giây xuống 0,15 mili giây, , Bảng quản trị > Cài đặt > Cấu hình chung.</li>
                               <li> [Đã sửa] 4 vấn đề bảo mật, về quyền riêng tư khi theo dõi, bắt buộc khi đăng nhập và hai xác thực, XSS trong tin nhắn bằng nodejs.</li>
                               <li> [Đã sửa] hơn 2 lỗi nhỏ khác.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1.4 <small>Ngày 23 tháng 09 năm 2022</small> </h6>
                          <ul>
                               <li> [Đã sửa] tính năng xóa nhiều người dùng không hoạt động từ bảng quản trị.</li>
                               <li> [Đã sửa lỗi] tải trang web chậm khi truy cập lần đầu.</li>
                               <li> [Đã sửa] thẻ br hiển thị trên giới thiệu, trang, nhóm và sản phẩm của người dùng.</li>
                               <li> [Đã sửa] wasabi không hoạt động với nodejs.</li>
                               <li> [Đã sửa] hình ảnh jpg với loại webp mime trả về hình ảnh rỗng. </li>
                               <li> [Đã sửa] video vẫn phát ngay cả khi bạn phát một video khác.</li>
                               <li> [Đã sửa] thanh toán coinbase trở lại lỗi máy chủ Internet 500 khi hủy thanh toán.</li>
                               <li> [Đã sửa] hệ thống hoàn thành hồ sơ không hoạt động ở chế độ Instagram.</li>
                               <li> [Đã sửa] Người kiểm duyệt không thể thêm phim [Đã sửa].</li>
                               <li> [Đã sửa] hiển thị số dư dài hạn trên trang thu nhập của tôi.</li>
                               <li> [Đã sửa] giới hạn bài đăng mỗi giờ không hoạt động.</li>
                               <li> [Đã sửa] Hơn 4 lỗi nhỏ khác.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1.3 <small>Ngày 09 tháng 09 năm 2022</small> </h6>
                          <ul>                         
                               <li> [Đã sửa] thiết kế trang tài trợ bị hỏng.</li>
                               <li> [Đã sửa lỗi] gửi tệp không được hỗ trợ trong cuộc trò chuyện sẽ không hiển thị cửa sổ bật lên có định dạng tệp sai.</li>
                               <li> [Đã sửa] khi bạn gửi tệp hoặc hình ảnh trong cuộc trò chuyện, nhấp vào hình ảnh sẽ không mở được.</li>
                               <li> [Đã sửa] "bây giờ" hiển thị trên thông báo.</li>
                               <li> [Đã sửa] các tệp không bị xóa khỏi bộ nhớ của bên thứ ba sau khi xóa bài đăng. </li>
                               <li> [Đã sửa] liên kết bài viết sẽ không mở được nếu có thêm dấu gạch chéo ở cuối.</li>
                               <li> [Đã sửa] Hơn 4 lỗi nhỏ khác.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1.2 <small>Ngày 02 tháng 09 năm 2022 [Cập nhật độ ổn định]</small> </h6>
                          <ul>
                               <li> [Đã thêm] biểu tượng cảm xúc mới vào tin nhắn và bài đăng.</li>
                               <li> [Đã thêm] kéo và thả để tải lên trang truyện.</li>
                               <li> [Đã thêm] hiệu ứng vô hình cho câu chuyện.</li>
                               <li> [Đã thêm] trình phát video mới.</li>
                               <li> [Đã thêm] trình phát video dành cho đào tạo kinh doanh.</li>
                               <li> [Đã thêm] kéo và thả để tạo trang album.</li>
                               <li> [Đã thêm] trình phát âm thanh khi trò chuyện khi gửi tệp ghi âm.</li>
                               <li> [Đã thêm] menu thả xuống mới trên tiêu đề, bài đăng và hồ sơ.</li>
                               <li> [Đã thêm] bản nâng cấp mới cho hệ thống chuyên nghiệp. Giờ đây, người dùng có thể nâng cấp lên gói Pro khác bằng cách sử dụng cùng một trang Go Pro thay vì sử dụng trang cài đặt.</li>
                               <li> [Đã thêm] tệp cron-job.php mới, (nên được thêm vào).</li>
                               <li> [Đã thêm] hệ thống ISO cho lang.</li>
                               <li> [Đã thêm] thẻ meta Href SEO.</li>
                               <li> [Đã thêm] BACKBLAZE đột quỵ.</li>
                               <li> [Đã thêm] khả năng tải tệp trực tiếp từ máy chủ lên các dịch vụ của bên thứ ba như S3.</li>
                               <li> [Đã thêm] điểm cuối tùy chỉnh cho mỗi bộ lưu trữ (hỗ trợ CDN).</li>
                               <li> [Đã thêm] biểu tượng phản ứng mới.</li>
                               <li> [Đã thêm] câu chuyện hoạt hình màu viền không nhìn thấy được (trang hồ sơ).</li>
                               <li> [Đã thêm] hơn 10 khu vực khác vào Wasabi, Ocean và Amazon.</li>
                               <li> [Đã thêm] khả năng chọn người có thể sử dụng hệ thống liên kết.</li>
                               <li> [Đã thêm] khả năng chỉnh sửa các phần diễn đàn và tên diễn đàn.</li>
                               <li> [Đã thêm] khả năng đặt số tiền rút tối thiểu tùy chỉnh.</li>
                               <li> [Đã thêm] trạng thái hệ thống vào bảng quản trị để kiểm tra các sự cố thường gặp.</li>
                               <li> [Đã thêm] nút "Thêm ảnh" để đăng hộp nhà xuất bản sau khi chọn hình ảnh.</li>
                               <li> [Đã thêm] API Google Dịch cho bài đăng.</li>
                               <li> [Đã thêm] hệ thống "Khả năng gửi email" để gỡ lỗi và kiểm tra nhật ký cài đặt SMTP. </li>
                               <li> [Đã thêm] tiếng Hindi, tiếng Urdu, tiếng Trung, tiếng Indonesia, tiếng Croatia, tiếng Do Thái, tiếng Bengali, tiếng Nhật, tiếng Bồ Đào Nha, tiếng Ý, tiếng Ba Tư, tiếng Thụy Điển, tiếng Việt, tiếng Đan Mạch và tiếng Philipin.</li>
                               <li> [Cải tiến] thiết kế/màu sắc trong chủ đề mặc định cho một số phần.</li>
                               <li> [Cải tiến] bảo mật mã.</li>
                               <li> [Đã xóa] Hơn 10 tệp không được sử dụng.</li>
                               <li> [Đã cập nhật] biểu tượng tải xuống cho thông báo thả xuống.</li>
                               <li> [Đã cập nhật] thiết kế danh sách người dùng ở thanh bên phải trong trang hồ sơ người dùng .</li>
                               <li> [Đã cập nhật] thiết kế trang đào tạo kinh doanh.</li>
                               <li> [Đã cập nhật] thiết kế trang tài trợ.</li>
                               <li> [Đã cập nhật] bộ chọn ngày cho các sự kiện, hồ sơ và các phần khác.</li>
                               <li> [Đã cập nhật] trang cài đặt người dùng.</li>
                               <li> [Đã cập nhật] thiết kế mô hình phím tắt.</li>
                               <li> [Đã cập nhật] biểu tượng tiêu đề.</li>
                               <li> [Đã cập nhật] Thiết kế "Hoàn thiện hồ sơ".</li>
                               <li> [Đã cập nhật] thiết kế thời trang.</li>
                               <li> [Đã cập nhật] trang khởi động. </li>
                               <li> [Đã cập nhật] thiết kế tab trò chuyện.</li>
                               <li> [Đã cập nhật] thiết kế trang ví.</li>
                               <li> [Đã cập nhật] thiết kế một số phần trong chủ đề.</li>
                               <li> [Đã sửa] trả lời tin nhắn về chủ đề ánh nắng (nodejs).</li>
                               <li> [Đã sửa lỗi] hộp thoại cuộc gọi video / âm thanh không đóng nếu có nhiều tab.</li>
                               <li> [Đã sửa] "đánh dấu tất cả tin nhắn" khi nút đọc bị treo.</li>
                               <li> [Đã sửa] hình dán không hoạt động trên nodejs.</li>
                               <li> [Đã sửa] Bộ lưu trữ FTP không hoạt động trên nodejs.</li>
                               <li> [Đã sửa] Liên kết SEO trên phim, thêm tiêu đề phim vào liên kết phim thay vì chỉ sử dụng /ID</li>
                               <li> [Đã sửa] hiển thị ký hiệu đô la trên trang điểm ngay cả khi bạn có đơn vị tiền tệ khác.</li>
                               <li> [Đã sửa] nhấp vào "Tìm kiếm nâng cao" đã chuyển hướng đến trang 404.</li>
                               <li> [Đã sửa] liên kết tạo blog có thể được truy cập ngay cả khi không được phép.</li>
                               <li> [Đã sửa] điểm không được thêm nếu hệ thống phê duyệt blog được bật.</li>
                               <li> [Đã sửa] blog không bị xóa nếu bạn xóa bài đăng trên blog.</li>
                               <li> [Đã sửa] Phát trực tiếp trên Agora.</li>
                               <li> [Đã sửa] Ví + Số dư hiển thị trên trang "Thu nhập của tôi".</li>
                               <li> [Đã sửa] thông báo trò chuyện nhóm (nodejs).</li>
                               <li> [Đã sửa] thẻ br hiển thị trên tiêu đề bài viết.</li>
                               <li> [Đã sửa] tệp video không bị xóa khỏi máy chủ (FFmpeg)</li>
                               <li> [Đã sửa] các trang/bài đăng được quảng cáo không được đặt lại sau khi tư cách thành viên chuyên nghiệp kết thúc.</li>
                               <li> [Đã sửa] 3 thông báo cảnh báo của nodejs.</li>
                               <li> [Đã sửa] nhận xét không hoạt động khi sử dụng tiếng Pháp.</li>
                               <li> [Đã sửa] khả năng tải lên nhiều hình ảnh trên sản phẩm.</li>
                               <li> [Đã sửa] wasabi không hoạt động ở khu vực phía đông mặc định.</li>
                               <li> [Đã sửa] Ký tự UTF-8 không hoạt động trên trò chơi.</li>
                               <li> [Đã sửa] "Kích thước tải lên tối đa" không cập nhật từ bảng quản trị.</li>
                               <li> [Đã sửa] người dùng có thể tải lên tệp âm thanh ngay cả khi nhóm người dùng không cho phép tải lên âm thanh.</li>
                               <li> [Đã sửa] thời tiết không hiển thị ở chủ đề ánh nắng.</li>
                               <li> [Đã sửa] tải bản ghi âm lên bằng cách sử dụng nodejs từ trang trò chuyện và tin nhắn.</li>
                               <li> [Đã sửa] không thể đăng nếu hệ thống phê duyệt bài đăng được bật từ bảng quản trị. </li>
                               <li> [Đã sửa] hơn 50 lỗi nhỏ về thiết kế và giao diện người dùng.</li>
                               <li> [Đã sửa] hơn 10 lỗi nhỏ khác.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1.1 <small>Ngày 08 tháng 7 năm 2022 </small></h6>
                          <ul>
                               <li> [Đã thêm] thời gian xem tin.</li>
                               <li> [Cải tiến] thiết kế/màu sắc trong chủ đề mặc định cho một số phần.</li>
                               <li> [Cải tiến] thiết kế trình phát âm thanh .</li>
                               <li> [Đã sửa] vấn đề tạo bài viết.</li>
                               <li> [Đã sửa lỗi] quyền riêng tư khi phát trực tiếp không cập nhật trong bảng quản trị.</li>
                               <li> [Đã sửa] chọn gói của bạn, các gói chuyên nghiệp không hiển thị trên trang chào mừng. </li>
                               <li> [Đã sửa] Sự cố CROS trong nodejs.</li>
                               <li> [Đã sửa] hệ thống ví không chấp nhận nạp tiền quá 1000</li>
                               <li> [Đã sửa] nút thông báo không hiển thị trên hồ sơ (di động).</li>
                               <li> [Đã sửa] {site_name} hiển thị trên trang đăng ký.</li>
                               <li> [Đã sửa] biểu đồ không hiển thị trên các nhóm và trang nếu tải bằng ajax.</li>
                               <li> [Đã sửa] các câu chuyện hiện được DESC sắp xếp thay vì ASC.</li>
                               <li> [Đã sửa] màu trò chuyện, màu mặc định là đen.</li>
                               <li> [Đã sửa] đôi khi hiển thị ngày sinh trống trên trang hồ sơ. </li>
                               <li> [Đã sửa] nhấp vào câu chuyện tiếp theo sẽ hiển thị câu chuyện tiếp theo.</li>
                               <li> [Đã sửa] giới hạn người ký tự trên trang quyền riêng tư.</li>
                               <li> [Đã sửa] việc vô hiệu hóa các trang đã vô hiệu hóa nút tạo ở tiêu đề trên cùng.</li>
                               <li> [Đã sửa] Video YouTube ở chế độ Instagram không hoạt động.</li>

                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1 <small>Ngày 01 tháng 07 năm 2022 </small></h6>
                          <ul>
                               <li> [Đã thêm] báo cáo hệ thống người dùng + lý do.</li>
                               <li> [Đã thêm] thông báo cấm trên hồ sơ người dùng nếu người dùng bị cấm. </li>
                               <li> [Đã thêm] Chế độ Instagram.</li>
                               <li> [Đã thêm] phương thức thanh toán Flutterwave.</li>
                               <li> [Đã thêm] Phương thức thanh toán Ngenius.</li>
                               <li> [Đã thêm] Phương thức thanh toán Aamarpay.</li>
                               <li> [Đã thêm] khả năng thêm các gói chuyên nghiệp tùy chỉnh.</li>
                               <li> [Đã thêm] khả năng thêm phương thức rút tiền tùy chỉnh. </li>
                               <li> [Đã thêm] khả năng chọn người có thể sử dụng một tính năng, Quản trị viên, Tất cả người dùng, Chỉ chuyên nghiệp.</li>
                               <li> [Đã thêm] khả năng gửi lại hai mã xác minh xác thực.</li>
                               <li> [Đã thêm] thiết kế mới cho chế độ Instegram.</li>
                               <li> [Đã thêm] chế độ nhà phát triển vào bảng quản trị.</li>
                               <li> [Đã cập nhật] tài liệu và câu hỏi thường gặp: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li >
                               <li> [Đã cập nhật] thiết kế trang xác minh email. </li>
                               <li> [Đã cập nhật] thiết kế trò chuyện.</li>
                               <li> [Đã cập nhật] tất cả các phần tử bóng của trang web (css).</li>
                               <li> [Đã cập nhật] thông báo tiêu đề, kích thước thả xuống của tin nhắn.</li>
                               <li> [Đã cập nhật] thiết kế bình luận bài đăng.</li>
                               <li> Thiết kế [Cải tiến] ở chủ đề mặc định cho một số phần.</li>
                               <li> [Đã sửa] qrcode.js bị thiếu dưới ánh nắng mặt trời.</li>
                               <li> Tìm kiếm [Đã sửa] trong bảng quản trị không hoạt động tốt.</li>
                               <li> [Đã sửa] đăng nhập bằng twitter.</li>
                               <li> [Đã sửa] Hoa hồng quản trị viên không xuất hiện khi mua sản phẩm.</li>
                               <li> [Đã sửa] Thẻ meta OG cho album.</li>
                               <li> [Đã sửa] Lỗ hổng XSS.</li>
                               <li> [Đã sửa] sản phẩm đã được sửa lỗi hiển thị còn hàng trong khi không còn hàng.</li>
                               <li> Thông báo [Đã sửa] không hoạt động.</li>
                               <li> [Đã sửa] video/cuộc gọi trực tiếp trên agora.</li>
                               <li> [Đã sửa] API đăng nhập google.</li>
                               <li> [Đã sửa] cuộc gọi video/âm thanh twilio.</li>
                               <li> [Đã sửa] nếu bài đăng được quảng cáo trên một trang thì bài đăng đó không xuất hiện trong phần bài đăng đã khởi động.</li>
                               <li> [Đã sửa] khả năng gửi gif & nhãn dán trên nodejs. </li>
                               <li> [Đã sửa] Hơn 40 lỗi nhỏ khác.</li>
                               <li> [Đã sửa] lỗi trong API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.0.1 <small>Ngày 23 tháng 02 năm 2022 </small></h6>
                          <ul>
                               <li> [Đã thêm] trình phát âm thanh cho các tệp mp3.</li>
                               <li> [Đã thêm] API yandex cho bản đồ. </li>
                               <li> [Đã thêm] phương thức thanh toán yandex.</li>
                               <li> [Đã thêm] phương thức thanh toán iyzipay.</li>
                               <li> [Đã thêm] phương thức thanh toán securionpay.</li>
                               <li> [Đã thêm] phương thức thanh toán Authorize.Net. </li>
                               <li> [Đã thêm] đăng nhập xã hội ok.ru.</li>
                               <li> [Đã thêm] API mới trong trang dành cho nhà phát triển: get_pages, get_groups, get_products, get_followers, get_following, get_friends</li>
                               <li> [Đã thêm] liên kết ứng dụng dành cho thiết bị di động trong trang chào mừng và thanh bên, được quản lý từ bảng quản trị -> thông tin trang web.</li>
                               <li> [Đã cập nhật] thiết kế ở một số phần.</li>
                               <li> [Đã cập nhật] tài liệu và câu hỏi thường gặp: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li >
                               <li> Giá [Đã sửa] không hiển thị trong sản phẩm.</li>
                               <li> [Đã sửa] liên kết không hoạt động trên trang hồ sơ.</li>
                               <li> [Đã sửa] tải ajax ở một vài trang.</li>
                               <li> [Đã sửa] hình ảnh bị hỏng khi nhập liên kết.</li>
                               <li> [Đã sửa] thêm dưới dạng hệ thống gia đình.</li>
                               <li> [Đã sửa] Lỗ hổng XSS.</li>
                               <li> [Đã sửa] Hơn 10 lỗi nhỏ khác.</li>
                               <li> [Đã sửa] lỗi trong API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.0 <small>Ngày 07 tháng 02 năm 2022 [Cập nhật giới hạn]</small></h6>
                          <ul>
                               <li> [Đã thêm] chế độ trang web, chuyển trang web của bạn ngay lập tức sang chế độ Linkedin. (Instagram, Twitter, AskFM, Patreon sắp ra mắt).</li>
                               <li> [Đã thêm] hệ thống thị trường, giờ đây người dùng có thể mua bán sản phẩm + hoa hồng quản trị viên. </li>
                               <li> [Đã thêm] trình quản lý quy tắc của người kiểm duyệt, giờ đây bạn có thể chọn những gì người kiểm duyệt có thể làm.</li>
                               <li> [Đã thêm] nhiều vị trí đặt quảng cáo hơn (việc làm, diễn đàn, phim, ưu đãi & tài trợ) & tùy chọn toàn bộ trang web.</li>
                               <li> [Đã thêm] hệ thống liên kết nhiều cấp.</li>
                               <li> [Đã thêm] thông báo cấm tùy chỉnh cho mọi người dùng. </li>
                               <li> [Đã thêm] khả năng dịch các trang thuật ngữ.</li>
                               <li> [Đã thêm] Phương thức thanh toán CoinBase. </li>
                               <li> [Đã thêm] hệ thống tìm kiếm mới cho chế độ Linkedin. </li>
                               <li> [Đã thêm] nhiều API hơn. </li>
                               <li> [Đã thêm] ReCaptcha để tạo trang bài viết. </li>
                               <li> [Đã thêm] Kho lưu trữ Wasabi.</li>
                               <li> [Đã thêm] trang chào mừng mới.</li>
                               <li> [Đã thêm] ghi nhớ tôi trên trang đăng nhập.</li>
                               <li> [Đã thêm] hỗ trợ nhiều ngôn ngữ cho các điều khoản, quyền riêng tư và giới thiệu về trang.</li>
                               <li> [Đã cập nhật] API hàng loạt.</li>
                               <li> [Đã cập nhật] API CoinPayments.</li>
                               <li> [Đã cập nhật] API Infobip.</li>
                               <li> [Đã cập nhật] thiết kế trang thị trường, việc làm và phim (chủ đề mặc định). </li>
                               <li> [Đã cập nhật] thiết kế ở một số trang khác (chủ đề mặc định).</li>
                               <li> [Đã cập nhật] SDK Twilio. </li>
                               <li> [Đã cập nhật] biểu tượng thanh bên trái. (chủ đề mặc định)</li>
                               <li> [Đã cập nhật] tài liệu và câu hỏi thường gặp: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li >
                               <li> [Đã xóa] Hơn 10.000 dòng mã lỗi thời. </li>
                               <li> [Đã có sẵn] Định dạng mã PHP (HTML sắp có trong bản cập nhật tiếp theo).</li>
                               <li> [Đã sửa] hình ảnh có phần mở rộng _small không bị xóa trên bộ nhớ từ xa.</li>
                               <li> [Đã sửa] hình mờ không hoạt động trên bài đăng hình ảnh.</li>
                               <li> [Đã sửa] tin nhắn của các thành viên trong gia đình.</li>
                               <li> [Đã sửa] tên người dùng tự động, lượt thích trang hoặc tham gia nhóm không hoạt động khi bạn đăng ký bằng ứng dụng.</li>
                               <li> [Đã sửa] đăng nhập bằng instagram không hoạt động.</li>
                               <li> [Đã sửa] thông báo quan email không hoạt động khi theo dõi, xem hồ sơ hoặc nhận xét.</li>
                               <li> [Đã sửa] nút kiểm tra digitalocean không hoạt động trong bảng quản trị.</li>
                               <li> [Đã sửa] Cuộc gọi âm thanh/video không hoạt động từ trang web đến ứng dụng bằng agora.</li>
                               <li> [Đã sửa] lỗi nghiêm trọng của trang "những điều phổ biến".</li>
                               <li> [Đã sửa] 2 lần khai thác XSS. <small style="color: red;">[Quan trọng!]</small> </li>
                               <li> [Đã sửa] trang trống khi thêm / vào url.</li>
                               <li> [Đã sửa] sơ đồ trang web không tạo ra hơn 50 nghìn liên kết.</li>
                               <li> [Đã sửa] nút đọc thêm trên thiết bị di động.</li>
                               <li> [Đã sửa] Hơn 30 lỗi nhỏ khác.</li>
                               <li> [Đã sửa] lỗi trong API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
              <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2.2 <small>Ngày 09 tháng 08 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] Palestine vào danh sách quốc gia.</li>
                                <li> [Đã xóa] các quy tắc nginx được lồng tiếng trong nginx.conf, cần phải cập nhật cho người dùng nginx. </li>
                                <li> [Đã thay thế] Thời tiết của Yahoo bằng nhà cung cấp mới https://openweathermap.org</li>
                                <li> [Đã sửa] video trực tiếp không hoạt động trên firefox.</li>
                                <li> [Đã sửa] vấn đề về điểm blog, người dùng sẽ nhận được điểm ngay sau khi phê duyệt.</li>
                                <li> [Đã sửa] quầy bán hàng gần đó. </li>
                                <li> [Đã sửa] sự cố ngắt dòng trong hệ thống trò chuyện của nodejs.</li>
                                <li> [Đã sửa] trang hoàn tiền không xuất hiện. </li>
                                <li> [Đã sửa] thêm trang phim trong quản trị viên, đôi khi trông có vẻ bị hỏng.</li>
                                <li> [Đã sửa] chi tiết ngân hàng không được cập nhật trong bảng quản trị. </li>
                                <li> [Đã sửa] vấn đề trong thiết kế.</li>
                                <li> [Đã sửa] bài đăng video trên MySQL 8 và PHP 8.</li>
                                <li> [Đã sửa] thêm nhiều lỗi nhỏ.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2.1 <small>Ngày 28 tháng 06 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] xóa tài khoản E-mail để Quản lý email trong bảng quản trị.</li>
                                <li> [Tái tổ chức] liên kết bảng quản trị, nội dung, văn bản và hệ thống lưu tự động được tạo.</li>
                                <li> [Đã sửa] đã thấy sự cố trên nodejs.</li>
                                <li> [Đã sửa] Hỗ trợ FTP trên nodejs.</li>
                                <li> [Đã sửa] "Xem bài đăng X" trên nguồn cấp tin tức (NodeJS).</li>
                                <li> [Đã sửa] 2 vấn đề bảo mật (quan trọng). </li>
                                <li> [Đã sửa] nhân đôi điểm khi đăng nhiều hình ảnh.</li>
                                <li> [Đã sửa] 500 Lỗi khi truy cập một trang mà không đăng nhập. </li>
                                <li> [Đã sửa] Trình tìm nạp URL, nó không tìm nạp URL từ blog WoWonder.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2 <small>Ngày 08 tháng 06 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng chỉnh sửa và dịch email từ bảng quản trị, trong Công cụ > Quản lý email.</li>
                                <li> [Đã thêm] thời gian hết hạn cho các liên kết đặt lại mật khẩu là 12 giờ.</li>
                                <li> [Đã thêm] FFMPEG cho cuộc trò chuyện video + tạo hình thu nhỏ + gỡ lỗi tính năng ffmpeg từ bảng quản trị + hỗ trợ video lên tới 4K, (Bật / Tắt).</li>
                                <li> [Đã thêm] trình tạo tên người dùng tự động, đối với người dùng đăng ký mới, người dùng không bắt buộc phải viết tên người dùng của họ. (Bật / Tắt)</li>
                                <li> [Đã thêm] API mới, hơn 40 API.</li>
                                <li> [Đã thêm] phản ứng cho tin nhắn, (ajax / nodejs). </li>
                                <li> [Đã thêm] hệ thống trả lời tin nhắn, (ajax / nodejs). </li>
                                <li> [Đã thêm] hệ thống phản ứng cho câu chuyện. </li>
                                <li> [Đã thêm] hệ thống trả lời cho các câu chuyện. </li>
                                <li> [Đã thêm] ảnh gif + nhãn dán vào hệ thống bình luận. </li>
                                <li> [Đã thêm] ảnh gif + nhãn dán vào hệ thống trả lời. </li>
                                <li> [Đã thêm] trò chuyện video của Agora. </li>
                                <li> [Đã thêm] hộp điều khoản sử dụng để liên hệ với chúng tôi. </li>
                                <li> [Đã thêm] khả năng xóa câu trả lời trong cuộc thăm dò ý kiến trong khi tạo câu trả lời.</li>
                                <li> [Đã thêm] đăng nhập bằng Mailru, Discord, WeChat và QQ.</li>
                                <li> [Đã thêm] khả năng xóa tin nhắn, câu chuyện, bài đăng, bài viết và thông báo của người dùng đã chọn khỏi bảng quản trị.</li>
                                <li> [Thêm lại] phiên bản tập lệnh trong thanh bên của bảng quản trị.</li>
                                <li> [Đã cập nhật] hệ thống trò chuyện video twilio. </li>
                                <li> [Đã cập nhật] đã thấy thông báo systemn (NodeJS). </li>
                                <li> [Đã sửa] Hơn 80 lỗi và cải tiến được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.3 <small>Ngày 12 tháng 04 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] hệ thống thông báo theo thời gian thực.</li>
                                <li> [Cải thiện] tốc độ tải máy chủ và tốc độ trang web.</li>
                                <li> [Đã xóa] Tất cả các khoảng thời gian, yêu cầu và vòng lặp ajax của PHP từ đầu cuối clinet (nếu bật nodejs) và được thay thế thành ổ cắm web thời gian thực.</li>
                                <li> [Đã sửa] Hơn 3 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.2 <small>Ngày 28 tháng 3 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] hỗ trợ cho PHP 8.0+ và MySQL 8.0</li>
                                <li> [Đã thêm] hệ thống tải ajax mới cho bảng quản trị, giờ đây các trang của bảng quản trị được tải thông qua ajax.</li>
                                <li> [Đã cập nhật] hệ thống trò chuyện của nodejs, giờ đây người dùng có thể thấy hành động nhập trên danh sách người dùng tin nhắn, cập nhật hình đại diện, tên và trạng thái theo thời gian thực.</li>
                                <li> [Đã cập nhật] Thư viện S3/Spaces. </li>
                                <li> Tốc độ [Cải thiện] trên PHP 8.0</li>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.1 <small>Ngày 05 tháng 03 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã sửa] Hơn 10 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1 <small>Ngày 04 tháng 03 năm 2021 </small></h6>
                            <ul>
                                <li> [Đã thêm] hệ thống nhắn tin mới được hỗ trợ bởi NodeJS và websockets, giờ đây trò chuyện nhanh hơn, thời gian thực và mượt mà hơn. </li>
                                <li> [Đã thêm] bảng quản trị mới v2, với nhiều tùy chọn.</li>
                                <li> [Đã thêm] hệ thống dấu thời gian mới, ví dụ: (1 phút trước -> 1 phút, 2 giờ trước -> 2 giờ, 1 tháng trước -> 4 tuần, 1 năm trước -> 1 năm)</li>
                                <li> [Đã thêm] thông báo mới cho bảng quản trị, giờ đây bạn sẽ nhận được thông báo về mọi khoản thanh toán ngân hàng mới, yêu cầu xác minh, v.v.</li>
                                <li> [Đã thêm] chế độ ban đêm cho bảng quản trị. </li>
                                <li> [Cải thiện] bảo mật. [Quan trọng] </li>
                                <li> [Đã sửa] Hơn 60 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.3 <small>Ngày 08 tháng 07 năm 2020 </small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng nhúng bài đăng từ các liên kết TikTok, Twitter và MP4. </li>
                                <li> [Cải thiện] bảo mật. [Quan trọng] </li>
                                <li> [Đã sửa] Hơn 10 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.3 <small>Ngày 08 tháng 07 năm 2020 </small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng chọn camera khi phát trực tiếp. </li>
                                <li> [Đã thêm] hình thu nhỏ cho video phát trực tiếp. </li>
                                <li> [Đã thêm] hình đại diện nữ cho người dùng nữ. </li>
                                <li> [Đã thêm] Thêm một số API nữa. (phương thức thanh toán) </li>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.2
                                <small>Ngày 26 tháng 05 năm 2020 </small></h6>
                            <ul>
                                <li> [Đã thêm] Phát trực tiếp Agora. </li>
                                <li> [Đã thêm] Thêm một số API nữa. </li>
                                <li> [Đã sửa] Hơn 40 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                                <li> [Cải tiến] Tốc độ tải.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.1
                                <small>Ngày 18 tháng 04 năm 2020 </small></h6>
                            <ul>
                                <li> [Đã sửa] hơn 10 lỗi.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0
                                <small>Ngày 16 tháng 04 năm 2020 [Giới hạn] </small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng chỉnh sửa/thêm/tắt phản ứng bài đăng. </li>
                                <li> [Đã thêm] hệ thống ký ức, người dùng có thể xem ký ức của mình vào ngày này.</li>
                                <li> [Đã thêm] phát trực tiếp cho bài đăng [bật/tắt] (trang web của bên thứ ba).</li>
                                <li> [Đã thêm] phân tích trang, xem lượt thích mới nhất mỗi tuần, tháng, năm và hôm nay.</li>
                                <li> [Đã thêm] phân tích nhóm, xem số lần tham gia mới nhất mỗi tuần, tháng, năm và hôm nay.</li>
                                <li> [Đã thêm] thông báo bài đăng trên blog, nhận thông báo khi ai đó nhận xét về bài đăng trên blog của bạn.</li>
                                <li> [Đã thêm] thông báo diễn đàn, nhận thông báo khi ai đó nhận xét về chủ đề diễn đàn của bạn.</li>
                                <li> [Đã thêm] khả năng yêu cầu thành viên khi đăng ký, [bật/tắt]</li>
                                <li> [Đã thêm] danh mục phụ cho các trang, nhóm và thị trường.</li>
                                <li> [Đã thêm] trường tùy chỉnh cho các trang, nhóm và thị trường. </li>
                                <li> [Đã thêm] thông báo về số ngày thành viên chuyên nghiệp còn lại. </li>
                                <li> [Đã thêm] thanh toán định kỳ cho hệ thống chuyên nghiệp.</li>
                                <li> [Đã thêm] khả năng chỉ người dùng chuyên nghiệp mới có thể tải lên [bật/tắt].</li>
                                <li> [Đã thêm] khả năng chỉ người dùng chuyên nghiệp mới có thể thực hiện cuộc gọi [bật/tắt]</li>
                                <li> [Đã thêm] hệ thống đánh giá/phê duyệt bài đăng trên blog. </li>
                                <li> [Đã thêm] khả năng yêu cầu hoàn tiền cho gói chuyên nghiệp [bật/tắt]</li>
                                <li> [Đã thêm] trang chính sách hoàn tiền. </li>
                                <li> [Đã thêm] phương thức thanh toán Paystack, Razorpay, Paysera và không dùng tiền mặt. </li>
                                <li> [Đã thêm] trang để hiển thị các cửa hàng/doanh nghiệp lân cận. </li>
                                <li> [Đã thêm] hệ thống ưu đãi cho các trang. </li>
                                <li> [Đã thêm] hệ thống mật khẩu phức tạp trên trang đăng ký. </li>
                                <li> [Đã thêm] ngăn chặn brutforce trên hệ thống đăng nhập, giới hạn đăng nhập thất bại mỗi phút.</li>
                                <li> [Đã thêm] khả năng người dùng có thể đăng bài trên các trang. [bật/tắt]</li>
                                <li> [Đã thêm] khả năng chủ sở hữu trang và nhóm có thể thêm người kiểm duyệt với một số đặc quyền nhất định.</li>
                                <li> [Đã thêm] Google Cloud để lưu trữ.</li>
                                <li> [Đã thêm] phương thức rút tiền từ tài khoản ngân hàng, người dùng có thể gửi thông tin ngân hàng của mình cho quản trị viên và quản trị viên có thể xem xét rồi phê duyệt.</li>
                                <li> [Đã thêm] hệ thống mô phỏng email. gửi email cho người dùng không đăng nhập lần X.</li>
                                <li> [Đã thêm] khả năng thêm trò chơi từ các trang web khác, không chỉ miniclip.</li>
                                <li> [Đã thêm] khả năng nhận thông báo khi người dùng đăng bài mới.</li>
                                <li> [Đã thêm] quảng cáo bên trong và bên trong bài viết.</li>
                                <li> [Đã thêm] khả năng người dùng tạo liên kết mời.</li>
                                <li> [Đã thêm] hộp thông báo, đăng bài ẩn danh.</li>
                                <li> [Đã thêm] khả năng nhận thông báo khi bạn bè đăng bài đăng mới.</li>
                                <li> [Đã sửa] Hơn 50 lỗi.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                                <li> [Đã sửa] Các vấn đề bảo mật quan trọng.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5.2
                                <small>Ngày 7 tháng 1 năm 2020 [Quan trọng]</small></h6>
                            <ul>
                                <li> [Đã thêm] nhấp vào nút để bình luận và trả lời.</li>
                                <li> [Đã sửa] lỗi.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                                <li> [Đã sửa] Các vấn đề bảo mật quan trọng.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5.1
                                <small>Ngày 17 tháng 12 năm 2019 [Quan trọng]</small></h6>
                            <ul>
                                <li> [Đã thêm] xem các nhóm đã tham gia và các trang đã thích từ một trang.</li>
                                <li> [Đã thêm] khả năng đính kèm ảnh trong phần trả lời nhận xét.</li>
                                <li> [Đã thêm] tệp bị thiếu từ v2.5</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5
                                <small>Ngày 16 tháng 12 năm 2019 [Cập nhật cải tiến]</small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng đăng xuất khỏi tất cả các phiên.</li>
                                <li> [Đã thêm] khả năng phê duyệt hoặc từ chối bài đăng, bật/tắt.</li>
                                <li> [Đã thêm] API mới. </li>
                                <li> [Đã thêm] tự động thích cho các trang và tự động tham gia cho các nhóm. </li>
                                <li> [Đã cập nhật] Thư viện PHP.</li>
                                <li> [Đã cập nhật] API đăng nhập Google.</li>
                                <li> [Cải tiến] thiết kế chủ đề mặc định.</li>
                                <li> [Đã cải thiện] tốc độ.</li>
                                <li> [Đã cải thiện] tiếng Anh ở một số phần.</li>
                                <li> [Đã sửa] Hơn 100 lỗi và sự cố được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>

                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.4
                                <small>Ngày 01 tháng 09 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] khả năng gửi tin nhắn đến các trang.</li>
                                <li> [Đã thêm] khả năng chấp nhận hoặc từ chối lời mời trò chuyện nhóm.</li>
                                <li> [Đã thêm] hệ thống việc làm [Đã thêm], giờ đây người dùng có thể tạo việc làm và tuyển dụng.</li>
                                <li> [Đã thêm] plugin thời tiết vào thanh bên. </li>
                                <li> [Đã thêm] trang thông tin phổ biến, giờ đây bạn có thể tìm thấy những người dùng phù hợp với thông tin của mình.</li>
                                <li> [Đã thêm] hệ thống cấp vốn [Đã thêm], người dùng có thể tạo tiền và được thanh toán.</li>
                                <li> [Đã thêm] API mới. </li>
                                <li> [Đã sửa] hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                                <li> [được cải thiện] tốc độ.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.3
                                <small>Ngày 11 tháng 7 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] một số API mới vào phiên bản 2.</li>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] lỗi trong API.</li>
                                <li> [Cải tiến] độ ổn định của script cho v2.4</li>
                                <li> [Được cải thiện] tốc độ.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.2
                                <small>Ngày 20 tháng 6 nắm 2019</small></h6>
                            <ul>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Được cải thiện] Tốc độ.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.1
                                <small>Ngày 2 tháng 6 năm 2019</small></h6>
                            <ul>
                                <li> [Đã sửa] Hơn 10 lỗi được báo cáo.</li>
                                <li> [Đã sửa] vấn đề bảo mật.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3
                                <small>Ngày 30 tháng 5 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] Quản lý loại tiền tệ từ bảng quản trị, thêm bất kỳ loại tiền tệ nào, xóa, xóa, một loại tiền tệ cho tất cả, chuyên nghiệp, quảng cáo và thị trường.</li>
                                <li> [Đã thêm] khả năng nhận xét về album và nhiều hình ảnh.</li>
                                <li> [Đã thêm] lọc nhận xét, hàng đầu và mới nhất. </li>
                                <li> [Đã thêm] khả năng công khai các diễn đàn, thị trường và sự kiện và Google có thể truy cập được. </li>
                                <li> [Đã thêm] khả năng bật / tắt phương thức thanh toán PayPal. </li>
                                <li> [Đã thêm] khả năng vô hiệu hóa ngôn ngữ mà không xóa ngôn ngữ đó. </li>
                                <li> [Đã thêm] khả năng bật/tắt tính năng chọc ghẹo và thông báo "chào buổi sáng". </li>
                                <li> [Đã thêm] khả năng người dùng đưa ra nhận xét về bài đăng trước khi chia sẻ. </li>
                                <li> [Đã thêm] khả năng chặn miền khỏi email khi đăng ký, ví dụ: chặn @gmail.com </li>
                                <li> [Đã thêm] nhúng kiểu sản phẩm vào tin nhắn. </li>
                                <li> [Đã thêm] bài đăng có màu, với khả năng quản lý, thêm, xóa và chỉnh sửa chúng. </li>
                                <li> [Đã thêm] 2Phương thức thanh toán Thanh toán. </li>
                                <li> [Đã thêm] tìm kiếm trên bảng quản trị.</li>
                                <li> [Đã thay đổi] hàm băm mật khẩu từ mã hóa sha1 sang mật khẩu_hash. </li>
                                <li> [Cải thiện] tốc độ ajax bằng cách giảm kích thước tệp request.php và tách các yêu cầu.</li>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] vấn đề về API.</li>
                                <li> [Đã sửa] vấn đề bảo mật.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2.2
                                <small>Ngày 12 tháng 4 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] tính năng nhúng âm thanh, giờ đây bạn có thể nhúng trình phát từ âm thanh sâu đến Wowonder.</li>
                                <li> [Đã sửa] Hơn 20 lỗi được báo cáo.</li>
                                <li> [Đã sửa] vấn đề bảo mật.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2.1
                                <small>Ngày 6 tháng 4 năm 2019</small></h6>
                            <ul>
                                <li>[Đã thêm] hỗ trợ cho PHP 7.3+</li>
                                <li>[Đã sửa] Hơn 30 lỗi được báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2
                                <small>Ngày 1 tháng 4 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] Khả năng thêm và quản lý giới tính từ bảng quản trị.</li>
                                <li> [Đã thêm] Khả năng kiếm điểm bằng cách tạo blog. </li>
                                <li> [Đã thêm] giới hạn điểm hàng ngày cho người dùng chuyên nghiệp và miễn phí. </li>
                                <li> [Đã thêm] Khả năng chỉnh sửa thông tin trò chuyện nhóm và hình đại diện.</li>
                                <li> [Đã thêm] Khả năng tắt tin nhắn từ bạn bè hoặc mọi người.</li>
                                <li> [Đã thêm] khả năng lọc ảnh khiêu dâm và khỏa thân bằng API Google Vision.</li>
                                <li> Người dùng [Đã thêm] sẽ yêu cầu xác minh email của mình nếu anh ấy thay đổi từ trang cài đặt, nếu tính năng xác minh email được bật.</li>
                                <li> [Đã thêm] hệ thống chia sẻ mới, với phong cách mới và khả năng chia sẻ lên dòng thời gian, nhóm và trang.</li>
                                <li> [Đã thêm] khả năng quản lý tên, biểu tượng, tính năng, giá cả của các gói chuyên nghiệp và tắt một trong số chúng</li>
                                <li> [Đã thêm] khả năng quản lý trang, nhóm, sản phẩm và danh mục blog từ bảng quản trị > quản lý các tính năng + tách biệt.</li>
                                <li> [Đã thêm] khả năng xem các phản ứng, lượt thích, lượt không thích trên nhận xét và câu trả lời.</li>
                                <li> [Đã thêm] khả năng xem phản ứng, lượt thích bài đăng trên mô hình mới.</li>
                                <li> [Đã thêm] thanh toán ngân hàng cho ví và chuyên nghiệp.</li>
                                <li> [Đã thêm] API trò chuyện nhóm, API album, API Pokes và một số API khác. </li>
                                <li> [Đã thêm] thông báo trò chuyện nhóm.</li>
                                <li> [Đã thêm] khả năng xóa bài đăng của người dùng chỉ bằng một cú nhấp chuột từ bảng quản trị. </li>
                                <li> [Đã thêm] hình ảnh xác thực để liên hệ với chúng tôi. </li>
                                <li> [Đã thêm] thiết kế trang tin nhắn mới cho chủ đề mặc định.</li>
                                <li> [Đã sửa] một số lỗi quan trọng.</li>
                                <li> [Đã sửa] mối đe dọa bảo mật, cần phải cập nhật URGENT.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.1.1
                                <small>Ngày 29 tháng 1 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] Tải xuống thông tin của tôi, người dùng có thể tải xuống thông tin cá nhân, trang, nhóm, bài đăng và bạn bè.</li>
                                <li> [Đã sửa] một số lỗi quan trọng.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.1
                                <small>Ngày 20 tháng 1 năm 2019</small></h6>
                            <ul>
                                <li> [Đã thêm] chủ đề mới, "ánh nắng".</li>
                                <li> [Đã thêm] hệ thống tin mới cho cả hai chủ đề. </li>
                                <li> [Đã thêm] hệ thống lọc trên thị trường, theo chủ đề mới. </li>
                                <li> [Đã thêm] số lượng bài đăng hashtag, theo chủ đề mới.</li>
                                <li> [Đã sửa] một số lỗi.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.3.1
                                <small>Ngày 30 tháng 10 năm 2018</small></h6>
                            <ul>
                                <li> [Đã sửa] một số lỗi quan trọng trong hệ thống ví và các lỗi lớn khác.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.3
                                <small>Ngày 16 tháng 10 năm 2018</small></h6>
                            <ul>
                                <li> [Đã thêm] hệ thống xác nhận khi người dùng đăng nhập từ vị trí mới. </li>
                                <li> [Đã thêm] hệ thống xác thực hai yếu tố bằng email hoặc điện thoại. </li>
                                <li> [Đã sửa] một số lỗi.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.2
                                <small>Ngày 9 tháng 10 năm 2018</small></h6>
                            <ul>
                                <li> [Đã thêm] trình phát video mới. </li>
                                <li> [Đã thêm] khả năng tắt/bật google maps.</li>
                                <li> [Đã thêm] khả năng quản trị viên nạp tiền vào bất kỳ ví người dùng nào.</li>
                                <li> [Đã thêm] IP vào trình quản lý phiên.</li>
                                <li> [Đã thêm] khả năng tắt/bật nhận xét trên mỗi bài đăng.</li>
                                <li> [Đã sửa] 9 lỗi được báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.1
                                <small>Ngày 5 tháng 10 năm 2018</small></h6>
                            <ul>
                                <li> [Đã sửa] 11 lỗi được báo cáo. </li>
                                <li> [Cải thiện] Tốc độ Script.</li>
                                <li> [Đã sửa] lỗ hổng bảo mật quan trọng.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0
                                <small>Ngày 30 tháng 9 năm 2018</small></h6>
                            <ul>


<li>[Đã thêm] lưu trữ không gian kỹ thuật.
</li>
<li>[Đã thêm] hệ thống chọc.
</li>
<li>[Đã thêm] hệ thống tương tác (Thích, Haha, wow, giận dữ, yêu thích).
</li>
<li>[Đã thêm] hệ thống quà tặng, người dùng có thể tặng quà cho người khác.
</li>
<li>[Đã thêm] số liệu và biểu đồ thống kê cho số lượt xem/nhấp quảng cáo mỗi ngày.
</li>
<li>[Đã thêm] Infobip tới nhà cung cấp SMS.
</li>
<li>[Đã thêm] stripe vào hệ thống ví như trên trang Go Pro.
</li>
<li>[Đã thêm] lấy lại mật khẩu bằng số điện thoại.
</li>
<li>[Đã thêm] phạm vi tiếp cận người dùng ước tính trên trang tạo quảng cáo.
</li>
<li>[Đã thêm] bitcoin (coinpayments) phương thức thanh toán cho hệ thống quảng cáo và Pro.
</li>
<li>[Đã thêm] Lịch sử giao dịch thanh toán cho các lần nạp tiền vào ví và hệ thống Pro, với khả năng bật hoặc tắt tính năng này.
</li>
<li>[Đã thêm] tùy chọn thay đổi số điện thoại từ trang cài đặt.
</li>
<li>[Đã thêm] trang bài viết phổ biến.
</li>
<li>[Đã thêm] phần ảnh và video vào hồ sơ.
</li>
<li>[Đã thêm] Nút kết thúc trò chuyện video.
</li>
<li>[Đã thêm] khả năng sử dụng phần trăm trong hệ thống Affiliate.
</li>
<li>[Đã thêm] telegram để chia sẻ lựa chọn.
</li>
<li>[Đã thêm] quản trị viên có thể vô hiệu hóa và kích hoạt liên kết chia sẻ mạng xã hội.
</li>
<li>[Đã thêm] nhiều biểu tượng cảm xúc hơn.
</li>
<li>[Đã thêm] phím tắt cho bài viết, nhấp vào "j" để chuyển sang bài viết tiếp theo.
</li>
<li>[Đã thêm] hệ thống điểm, người dùng có thể kiếm điểm cho các bài đăng, nhận xét, lượt thích, lượt không thích, thắc mắc và phản ứng. (Người dùng có thể dành điểm cho các chuyên gia hoặc quảng cáo hoặc anh ta có thể yêu cầu chúng dưới dạng đô la).
</li>
<li>[Đã thêm] nhãn dán để trò chuyện và tin nhắn.
</li>
<li>[Đã thêm] hệ thống xoay hình ảnh..
</li>
<li>[Đã thêm] Quản lý ứng dụng dành cho nhà phát triển từ bảng quản trị.
</li>
<li>[Đã thêm] Báo cáo bình luận cho quản trị viên.
</li>
<li>[Đã thêm] Hệ thống tìm kiếm nâng cao cho các trường tùy chỉnh.
</li>
<li>[Đã thêm] Đã thêm lọc theo độ tuổi và được xác minh vào hệ thống tìm kiếm.
</li>
<li>[Đã thêm] nhóm/trang được đề xuất trong nhóm và trang của tôi.
</li>
<li>[Đã thêm] hệ thống tìm kiếm trong blog.
</li>
<li>[Đã thêm] hệ thống kết bạn tự động (Tự động theo dõi/kết bạn với người dùng mới đăng ký).
</li>
<li>[Đã thêm] khả năng xem bạn bè chung từ hồ sơ (hệ thống bạn bè).
</li>
<li>[Đã thêm] khả năng biết ai đã xem tin của bạn thông qua thông báo.
</li>
<li>[Đã thêm] Kiểm tra ReCaptcha để quên mật khẩu (bảo mật).
</li>
<li>[Đã thêm] thông báo bình luận blog.
</li>
<li>[Đã thêm] Thông báo qua email khi tài khoản của người dùng bị xóa.
</li>
<li>[Đã thêm] một tin nhắn cảnh báo trước khi hủy kết bạn với ai đó.
</li>
<li>[Đã thêm] trình quản lý (người dùng có thể xem/quản lý trình duyệt/nền tảng nơi họ đăng nhập).
</li>
<li>[Đã thêm] hệ thống quản lý thông báo (Người dùng có thể chọn loại thông báo họ muốn nhận).
</li>
<li>[Đã thêm] khả năng thêm người theo dõi cho một người dùng cụ thể bằng ID, trong Quản trị viên > Người dùng (Chỉ được bật trong hệ thống theo dõi).
</li>
<li>[Đã thêm] hệ thống danh sách đen, quản trị viên có thể đưa email, tên người dùng và địa chỉ IP vào danh sách đen.
</li>
<li>[Đã thêm] hệ thống hoạt động, người dùng có thể xem các hoạt động của chính mình từ hồ sơ của mình (thích, không thích, phản ứng, thắc mắc, bình luận, trả lời, theo dõi, bạn bè).
</li>
<li>[Đã thêm] khả năng người dùng chọn xem hồ sơ của họ có được tìm thấy/lập chỉ mục bởi các công cụ tìm kiếm hay không.
</li>
<li>[Đã cải thiện] tốc độ tải.
</li>
<li>[Đã nén] Các tệp JS thành ít tệp hơn.
</li>
<li>[Đã sửa] lỗi trên API.
</li>
<li>[Đã sửa] lỗi lớn trong script. (+10)
</li>
<li>[Đã sửa] 3 vấn đề bảo mật.</li>


                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6.2
                                <small>Ngày 27 tháng 6 năm 2018</small></h6>
                            <ul>
                                <li> [Đã thêm] Trang chào mừng mới cho chủ đề mặc định. </li>
                                <li> [Đã thêm] Hỗ trợ lưu trữ Wasabi.</li>
                                <li> [Đã nâng cấp] PHPMailer lên v6.</li>
                                <li> Đã sửa hơn 10 lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6.1
                                <small>Ngày 13 tháng 6 năm 2018</small></h6>
                            <ul>
                                <li> [Đã thêm] chủ đề mặc định về trạng thái ngày (chào buổi sáng etc).</li>
                                <li> [Đã cải thiện] thiết kế chủ đề và hình thức.</li>
                                <li> [Đã cải thiện] sự ổn định của hộp.</li>
                                <li> [Đã loại bỏ] Tiện ích báo cáo thời tiết từ chủ đề do vấn đề bản quyền.</li>
                                <li> Đã sửa hơn 10 lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
              <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6
                                <small>Ngày 27 tháng 5 năm 2018</small></h6>
                            <ul>
                                <li> [Đã thêm] Máy chủ FTP client để lưu trữ tập tin, ảnh, video trên thiết bị khác.</li>
                                <li> [Đã thêm] Tuân thủ GDPR (cookie frame, checkboxes, chính sách bảo mật)</li>
                                <li> [Đã thêm] tài liệu APIv2 hoàn toàn mới.</li>
                                <li> [Đã thêm] khả năng chỉnh sửa đào tạo kinh doanh từ bảng quản trị.</li>
                                <li> [Đã thêm] khả năng đăng cảm xúc trên bài đăng, bình luận, và tin nhắn.</li>
                                <li> [Đã thêm] hệ thống tự động xóa cho người dùng và bài đăng dài hơn X ngày.</li>
                                <li> [Đã thêm] hệ thống cắt cho ảnh dại diện người dùng.</li>
                                <li> [Đã dịch] tất cả tiêu đề của trang.</li>
                                <li> [Đã cải thiện] tải tốc độ bài viết về chủ đề.</li>
                                <li> [Đã sửa] 3 vấn đề bảo mật.</li>
                                <li> [Đã sửa] hơn 50 lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.3
                                <small>Ngày 17 tháng 4 năm 2018</small></h6>
                            <ul>
                                <li> Đã thêm hai khóa cho OneSignal.</li>
                                <li> Đã thêm API gọi video cho ứng dụng điện thoại.</li>
                                <li> Đã cải thiện hệ thống bộ nhớ cho người dùng dữ liệu.</li>
                                <li> Đã sửa tất cả các lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.2
                                <small>Ngày 6 tháng 4 năm 2018</small></h6>
                            <ul>
                                <li> Đã cải thiện tải nội dung và máy chủ tải nhanh lên đến 50%.</li>
                                <li> Đã sửa tất cả lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.1
                                <small>Ngày 29 tháng 3 năm 2018</small></h6>
                            <ul>
                                <li> Đã sửa vấn đề đăng nhập facebook / google.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5
                                <small>Ngày 20 tháng 3 năm 2018</small></h6>
                            <ul>
                                <li> Đã thêm chủ đề mới (mặc định).</li>
                                <li> Đã khắc phục sự cố và lỗ hổng bảo mật cao.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.3
                                <small>Ngày 30 tháng 1 năm 2018 (Cập nhật quan trọng!)</small></h6>
                            <ul>
                                <li> Đã khắc phục sự cố và lỗ hổng bảo mật cao.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.2
                                <small>Ngày 4 tháng 1 năm 2018</small></h6>
                            <ul>
                                <li> Đã thêm đơn vị tiền tệ Ấn độ.</li>
                                <li> Đã thêm API mới cho đào tạo kinh doanh, tin.</li>
                                <li> Đã sửa hơn 7 lỗi báo cáo quan trọng.</li>
                                <li> Kiểm tra độ ổn định Script.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.1
                                <small>Ngày 22 tháng 12 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm kiểm soát bộ nhớ trong tập tin chủ Amazon.</li>
                                <li> Đã sửa hơn 5 lỗi báo báo quan trọng.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4
                                <small>Ngày 13 tháng 12 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm khả năng cho người dùng gửi tiền bằng số dư ví của họ.</li>
                                <li> Đã thêm thông báo tin nhắn Email cho người dùng ngoại tuyến. </li>
                                <li> Đã thêm khả năng nhập ảnh từ liên kết trong hệ thống bài đăng. </li>
                                <li> Đã thêm hệ thống hồ sơ. (Điền thông tin chi tiết của bạn cho người dùng mới). </li>
                                <li> Đã thêm new pagination hệ thống phân trang mới để tìm kiếm tính năng trong bảng quản trị (Người dùng, Trang, Nhóm, Bài đăng).</li>
                                <li> Đã thêm nơi quảng cáo mới trong hệ thống quảng cáo (Người dùng có thể tạo quảng cáo trên bài đăng video).</li>
                                <li> Đã thêm hỗ trợ Iframe cho chỉnh sửa diễn đàn. </li>
                                <li> Đã thêm chia sẻ nút wowonder trong nhật ký.</li>
                                <li> Đã thêm khả năng cho người dùng chọn đồng ý mặc định khi tải lên video trong ô nhà sản xuất.</li>
                                <li> Đã thêm tích hợp playtube video player.</li>
                                <li> Đã thay đổi video người chơi to mediaelement.js </li>
                                <li> Sự kiện hết hạn sẽ tự động bị xóa.</li>
                                <li> Chi tiết quản trị viên trong hệ thống thông báo hàng loạt và thay thế nó với biểu tượng yêu thích/tên trang.</li>
                                <li> Được thay đổi thiết kế hệ thống nhật ký.</li>
                                <li> Đã sửa hơn 7 lỗi báo cáo.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3.2
                                <small>Ngày 15 tháng 11 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm nhiều vùng trong Amazon S3. </li>
                                <li> Đã thêm khám phá liên kết thanh bên trái. </li>
                                <li> Đã sửa hơn 15 lỗi báo cáo. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3.1
                                <small>Ngày 21 tháng 10 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm tùy chỉnh đơn vị tiền tệ cho hệ thống quảng cáo. </li>
                                <li> Đã thêm thông báo đẩy web. </li>
                                <li> Đã thêm tùy chỉnh CSS / JS trong bảng quản trị. </li>
                                <li> Đã sửa hơn 10 lỗi báo cáo. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3
                                <small>Ngày 1 tháng 10 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm bảng quản trị mới. </li>
                                <li> Đã thêm hệ thống thông báo đẩy cho tất cả trang thông báo. </li>
                                <li> Đã thêm khả năng vô hiệu hóa nút cười/không thích. </li>
                                <li> Đã thêm tập tin API mới, tìm kiếm bạn bè, sự kiện, tin tạo trang nhóm và sự kiện. </li>
                                <li> Đã thêm hỗ trợ cho Opera mini and trình duyệt UC. </li>
                                <li> Đã sửa hơn 15 lỗi báo cáo. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.2
                                <small>Ngày 4 tháng 9 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm lựa chọn chính sách bảo mật cho người dùng "Chia sẻ vị trí của bạn công khai?". </li>
                                <li> Đã thêm tin của bạn bè ở trang chủ. </li>
                                <li> Người dingf có thể xem quảng cáo của họ. </li>
                                <li> Đã thêm lựa chọn tải ảnh lên trong hệ thống nhật ký. </li>
                                <li> Đã thêm nhiều đơn vị tiền tệ trong phân loại. </li>
                                <li> Đã thêm video trò chuyện API cho ứng dụng windows. </li>
                                <li> Đã thêm giá quảng cáo trong trang tạo quảng cáo. </li>
                                <li> Đã cải thiện xem thiết kế quảng cáo. </li>
                                <li> Đã cải thiện bảng quản trị, đã thay đổi bảng cơ sở dữ liệu.js </li>
                                <li> Người dùng không thể tạo quảng cáo nếu ví tiền rỗng. </li>
                                <li> Đã sửa hơn 40 lỗi báo cáo/cải tiến. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.1
                                <small>Ngày 27 tháng 8 năm 2017</small></h6>
                            <ul>
                                <li> Đã sửa tất cả lỗi báo cáo. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5
                                <small>Ngày 24 tháng 8 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống quảng cáo. (Nhấn chọn) </li>
                                <li> Đã thêm hệ thống tin. (trạng thái, Tự động loại bỏ sau 24 giờ).  </li>
                                <li> Đã thêm hệ thống bình luận mới cho bài viết và đào tạo kinh doanh. </li>
                                <li> Đã thêm hệ thống tin nhắn nhóm. </li>
                                <li> Đã thêm hệ thống tin nhắn hàng loạt trong bảng quản trị. </li>
                                <li> Đã thêm khả năng chỉnh sửa phản hồi bình luận. </li>
                                <li> Đã thêm khả năng xóa bài đăng trực tiếp từ trang chủ (quản trị viên). </li>
                                <li> Đã thêm khả năng xóa nhiều bình luận (quản trị viên). </li>
                                <li> Đã thêm giấu tính năng bài đăng. </li>
                                <li> Đã thêm hơn 30 cảm xúc. </li>
                                <li> Đã thêm toàn bộ mẫu xác thực (ID, ảnh, mô tả). </li>
                                <li> Đã thêm hệ thống chia sẻ bài đăng mới. </li>
                                <li> Đã thêm tạo trang bản đồ. </li>
                                <li> Đã thêm hệ thống đăng ký mời (Người dùng chỉ có thể đăng ký cùng liên kết mời). </li>
                                <li> Đã thêm kiểu tập ảnh mới (Collapsed). </li>
                                <li> Đã thêm thanh bảng điều khiển mới (Collapsed). </li>
                                <li> Đã thêm khả năng chọn người dùng đặc biệt trong danh sách Mailing. </li>
                                <li> Đã thêm khả năng kích hoạt/vô hiệu hóa hệ thống quản cáo, tin. </li>
                                <li> Đã thêm quản lý quảng xóa, tin (trạng thái) trong bảng quản trị. </li>
                                <li> Đã thêm lựa chọn chính sách bảo mật "Ai có thể nhìn thấy danh sách bạn bè của bạn?". </li>
                                <li> Đã thêm hỗ trợ định dạng nhiều ngày tháng. </li>
                                <li> Đã thêm khả năng mất xác thực nếu tên người dùng đã thay đổi. </li>
                                <li> Đã thêm hỗ trợ liên kết youtube/video cho hệ thống đào tạo kinh doanh</li>
                                <li> Đã thêm nhiều quản trị viên cho nhóm và trang. </li>
                                <li> Đã thêm sử dụng gifs "Giphy" API cho tin nhắn/bình luận. </li>
                                <li> Đã thêm hỗ trợ API cho ứng dụng IOS sắp tới. </li>
                                <li> Đã thêm hộp cho ảnh trên tin nhắn, bình luận và phản hồi. </li>
                                <li> Đã thêm hệ thống tỷ lệ trang, người dùng có thể đánh giá trang từ 0/5. </li>
                                <li> Đã thêm hệ thống báo cáo cho hồ sơ, trang và nhóm. </li>
                                <li> Đã thêm API mới cho ứng dụng windows máy tính bàn. </li>
                                <li> Đã thêm danh sách thành viên gia đình (thêm một bạn như em trai, bố, etc..) </li>
                                <li> Đã thêm phân loại mối quan hệ, ví dụ: Lisa đang trong mối quan hệ với Zach </li>
                                <li> Đã thêm tìm kiếm bạn bè gần đây (tìm kiếm bạn bè trong 100KM). </li>
                                <li> Đã thêm thông báo phản hồi nếu tập tin thể loại/tiện ích là không được hỗ trợ. </li>
                                <li> Đã thêm thông báo nếu tập tin lớn hơn kích thước cho phép trong ô mở, tin nhắn và trò chuyện.</li>
                                <li> Hệ thống băm mật khẩu được nâng cấp từ MD5 lên SHA1 </li>
                                <li> Đã thay đổi hệ thống xu hướng được cập nhật mỗi tuần. </li>
                                <li> Cập nhật thư viện font-awesome. </li>
                                <li> Cập nhật thư viện cảm xúc. </li>
                                <li> Sửa lỗi trong API. </li>
                                <li> Sửa các lỗi lớn trong script. (+30) </li>
                                <li> Đã cải thiện tốc độ tải. </li>
                                <li> Đã sửa 2 vấn đề bảo mật. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5.2
                                <small>Ngày 18 tháng 6 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống ghi audio để đăng/bình luận. </li>
                                <li> Nâng cấp API để phiên bản mới nhất cho tải lên tin nhắn android.  </li>
                                <li> Đã sửa lỗi trong script.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5.1
                                <small>Ngày 6 tháng 6 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống đào tạo kinh doanh. </li>
                                <li> Đã thêm hệ thống dịch bài viết. </li>
                                <li> Đã thêm hệ thống xem video. </li>
                                <li> Đã sửa lỗi twilio SMS. </li>
                                <li> Đã sửa lỗi trong ứng dụng riêng API. </li>
                                <li> Đã sửa một ít lỗi trong script. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5
                                <small>Ngày 25 tháng 5 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống diễn đàn. </li>
                                <li> Đã thêm hệ thống sự kiện.  </li>
                                <li> Đã thêm "Đăng nhập cùng WoWonder" tính năng API + ứng dụn + tài liệu.   </li>
                                <li> Đã thêm nút "tải nhiều hơn" để tìm kiếm trang.   </li>
                                <li> Đã thêm nút "chia sẻ trong wowonder" cho trang web + tài liệu của bên thứ ba.    </li>
                                <li> Đã thêm màu tùy chỉnh cuộc trò chuyện cho cuộc hội thoại.   </li>
                                <li> Đã thêm hỗ trợ thông báo đẩy cho tin nhắn Android.   </li>
                                <li> Đã sửa lỗi video/audio.  </li>
                                <li> Đã sửa lỗi trong ứng dụng riêng của API.   </li>
                                <li> Đã sửa một ít lỗi trong script.  </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.5
                                <small>Ngày 11 tháng 4 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống nhật ký. </li>
                                <li> Phát hành cuối cho hệ thống API. </li>
                                <li> Đã sửa một ít lỗi. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.4
                                <small>Ngày 2 tháng 3 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống cập nhật tự động. </li>
                                <li> Đã thêm hỗ trợ URL viết lại máy chủ (web.config). </li>
                                <li> Đã sửa một ít lỗi trong API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.3
                                <small>Ngày 23 tháng 2 năm 2017</small></h6>
                            <ul>
                                <li> Đã cải thiện chủ đề script.</li>
                                <li> Nâng cấp thư viện jQuery. </li>
                                <li> Tăng tốc độ script. </li>
                                <li> Đã sửa một ít lỗi trong API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.2
                                <small>Ngày 10 tháng 2 năm 2017</small></h6>
                            <ul>
                                <li> Đã cập nhật API cho tin nhắn IOS.</li>
                                <li> Đã sửa một ít lỗi trong script. </li>
                                <li> Đã sửa một ít lỗi trong API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.1
                                <small>Ngày 27 tháng 1 năm 2017</small></h6>
                            <ul>
                                <li> Đã cập nhật thư viện Hybridauth (lỗi đăng nhập Facebook). </li>
                                <li> Đã sửa nhiều hơn 3 lỗi. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4
                                <small>Ngày 11 tháng 1 năm 2017</small></h6>
                            <ul>
                                <li> Đã thêm "đọc nhiều hơn" trong mô tả sản phẩm. </li>
                                <li> Đã thêm lựa chọn tùy chỉnh phân loại đơn vị tiền tệ. </li>
                                <li> Đã thêm lựa chọn thể loại tùy chỉnh trong bảng quản trị. </li>
                                <li> Đã cập nhật thư viện PHPmailer (lỗi bảo mật).</li>
                                <li> Đã cập nhật thư viện Hybridauth (lỗi đăng nhập Google+). </li>
                                <li> Đã sửa "copyright" trong chân trang. </li>
                                <li> Đã sửa vấn đề thiết kế RTL. </li>
                                <li> Đã sửa vấn đề UTF-8 trong hệ thống gắn thẻ. </li>
                                <li> Đã sửa mã lỗi JavaScript trong sản phẩm Apple. </li>
                                <li> Đã sửa yêu cầu Android / Windows tin nhắn API. </li>
                                <li> Tối ưu hóa bảng quản trị. </li>
                                <li> Đã sửa nhiều hơn 5 lỗi. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.3
                                <small>Ngày 8 tháng 12 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm khả năng dịch trường tùy chỉnh. </li>
                                <li> Đã thêm khả năng thêm/chỉnh sửa/loại bỏ ngôn ngữ từ bảng quản trị. </li>
                                <li> Đã thêm gọi audio. </li>
                                <li> Đã thêm tích hợp cùng <a href="https://codecanyon.net/item/wowonder-android-messenger-mobile-application-for-wowonder/19034167?s_rank=1">tin nhắn WoWonder Android </a>.</li>
                                <li> Đã thêm khả năng quản lý thời gian thành viên Pro. </li>
                                <li> Đã thêm nút quản lý và hủy khi hết hạn người dùng Pro. </li>
                                <li> Đã thêm Twilio API cho gửi tin nhắn SMS. </li>
                                <li> Đã thêm android API cho ứng dụng sắp ra mắt. </li>
                                <li> Đã thêm Alipay trong Stipe. </li>
                                <li> Đã thêm trực tuyến bài đăng hashtag. </li>
                                <li> Đã thêm YouTube trong trang cài đặt liên kết mạng xã hội. </li>
                                <li> Đã thêm vị trí vào hệ thống phân loại. </li>
                                <li> Đã cải thiện cấu trúc cơ sở dữ liệu. </li>
                                <li> Đã cải thiện truy vấn SQL. </li>
                                <li> Đã cải thiện tốc độ script. </li>
                                <li> Tối ưu hóa Thiết kế/Code. </li>
                                <li> Sửa lỗi trong hệ thống tin nhắn. </li>
                                <li> Sửa một vài lỗi. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.2
                                <small>Ngày 10 tháng 10 năm 2016</small></h6>
                           <ul>
                                <li> Đã thêm tích hợp Amazon S3. </li>
                                <li> Đã thêm khả năng xóa tất cả hội thoại. </li>
                                <li> Đã thêm khả năng xóa tin nhắn người nhận. </li>
                                <li> Đã thêm hỗ trợ Nginx. </li>
                                <li> Đã sửa vấn đề trong hệ thống đăng nhập. </li>
                                <li> Đã sửa một vấn đề trong khi xóa trang từ bảng quản trị. </li>
                                <li> Đã sửa vài lỗi. </li>
                           </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.1
                                <small>Ngày 3 tháng 10 năm 2016</small></h6>
                            <ul>
                                <li> Nhiều hơn tuổi 10+ và sửa lỗi mới. </li>
                                <li> Tối ưu hóa thiết kế/Code. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4
                                <small>Ngày 25 tháng 9 năm 2016</small></h6>
                            <ul>
                                <li>Đã thêm trang chào mừng mới. </li>
                                <li>Đã thêm hệ thống trường tùy chỉnh. </li>
                                <li>Đã thêm hệ thống phân loại. </li>
                                <li>Đã thêm hệ thống tất cả affiliates + thanh toán. </li>
                                <li>Đã thêm hệ thống thăm dò ý kiến. </li>
                                <li>Đã thêm hệ thống trang tùy chỉnh. </li>
                                <li>Đã thêm phương thức thanh toán, (thẻ tín dụng Bitcoin, american express). </li>
                                <li>Đã thêm trường YouTube trong liên kết mạng xã hội. </li>
                                <li>Đã thêm tích hợp với <a href="https://codecanyon.net/item/wowonder-desktop-a-windows-messenger-for-wowonder/18029772">Windows Desktop Messenger</a>. </li>
                                <li>Đã thêm hệ thống người cập nhật bài đăng mới(Like twitter). </li>
                                <li>Đã thêm hệ thống ảnh trong bình luận. </li>
                                <li>Đã thêm tất cả mã tin nhắn cho windows / Android / IOS. </li>
                                <li>Đã thêm dự án CSRF cho yêu cầu mẫu / ajax requests. </li>
                                <li>Đã thêm liên kết điều khoản để đăng ký trang. </li>
                                <li>Đã thêm lựa chọn để kích hoạt/vô hiệu hóa âm thanh thông báo. </li>
                                <li>Đã thêm lựa chọn cho người dùng lọc bài viết theo tất cả hoặc người theo dõi. </li>
                                <li>Đã thêm nơi quảng cáo (giữa các bài đăng). </li>
                                <li>Đã thêm 'sản phẩm mới nhất' trong thanh. </li>
                                <li>Đã thêm thời gian người dùng dài hơn. </li>
                                <li>Đã thêm hệ thống thiết kế mới cho tin nhắn. </li>
                                <li>Đã thêm tùy chỉnh nền cho trang. </li>
                                <li>Đã thay thế hệ thống thu thập URL bằng hệ thống tốt hơn. </li>
                                <li>Tệp style.css được mã hóa thành .scss để dễ dàng mã hóa và xuất ra.</li>
                                <li>Tối ưu hóa tốc độ/Thiết kế/Code. </li>
                                <li>Đã sửa vấn đề Hashtag. </li>
                                <li>Đã sửa vấn đề chính sách bảo mật ngày sinh. </li>
                                <li>Đã sửa vấn đề xoay ảnh. </li>
                                <li>Đã sửa vấn đề cắt ảnh. </li>
                                <li>Đã sửa bảo mật chiếm quyền điều khiển.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.4
                                <small>Ngày 27 tháng 6 năm 2016</small></h6>
                            <ul>
                                <li> Đã sửa tất cả lỗi báo cáo. </li>
                                <li> Tăng tốc độ script lên 50%. </li>
                                <li> Tối ưu hóa thiết kế/mã. </li>
                                <li> Nâng cấp tối ưu hóa hệ thống ảnh sang cấp độ tiếp theo. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.3
                                <small>Ngày 19 tháng 6 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống gọi video/trò chuyện cho tất cả thiết bị. </li>
                                <li> Đã thêm lựa chọn xem tất cả bài viết hoặc theo dõi bài viết. </li>
                                <li> Đã thêm lựa chọn kích hoạt/vô hiệu hóa "người phát triển" trang. </li>
                                <li> Đã thêm lựa chọn để kích hoạt/vô hiệu hóa người dùng đăng ký. </li>
                                <li> Đã thêm "chế độ bảo trì" để tắt toàn bộ trang. </li>
                                <li> Đã thêm lựa chọn gửi danh sách mail đến người dùng "hoạt động, không hoạt động, tất cả" . </li>
                                <li> Đã thêm "nút vô hiệu hóa" màu nền ở bảng quản trị. </li>
                                <li> Đã thêm menu thả xuống cho nút tin nhắn ở tiêu đề.</li>
                                <li> Đã thêm trường giới tính cho đăng nhập mạng xã hội Facebook. </li>
                                <li> Đã thêm theo dõi tăng cường tối đa bài viết/trang cho người dùng Pro ở bảng quản trị. </li>
                                <li> Đã thêm "eapi link" cho gửi SMS. </li>
                                <li> Đã thêm nhiều tab trò chuyện (tối  3 tabs). </li>
                                <li> Đã thêm lựa chọn để thay đổi biểu tượng yêu thích từ bảng quản trị. </li>
                                <li> Đã thêm dự án CSRF cho mẫu. </li>
                                <li> Đã nâng cấp hệ thống trò chuyện và tin nhắn. </li>
                                <li> Cập nhật API tới v1.3.1 </li>
                                <li> Tối ưu hóa bố cục bảng quản trị.</li>
                                <li> Đã sửa lỗi. </li>
                                <li> Tối ưu hóa tốc độ/Thiết kế/Code. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.2
                                <small>Ngày 17 tháng 5 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm khả năng kích hoạt/vô hiệu hóa ứng dụng hỗ trợ, trang, nhóm. </li>
                                <li> Đã thêm sao lưu toàn hệ thống (Sao lưu tập tin của bạn, cơ sở dữ liệu, tải lên dễ dàng cùng 1 chọn ở bảng điều khiển). </li>
                                <li> Đã thêm thể loại đơn vị tiền tệ cho thanh toán, (RUB, PLN, ILS, BRL). </li>
                                <li> Đã thêm tính năng kéo làm mới ứng dụng Android </li>
                                <li> Đã thêm cấu hình kiểm tra đăng nhập PayPal.</li>
                                <li> Tăng tốc tải thời gian. </li>
                                <li> Đã sửa lỗi chuyển hướng, (www or without www). </li>
                                <li> Đã sửa ngôn ngữ mặc định khi đăng ký. </li>
                                <li> Đã sửa lỗi chung. </li>
                                <li> Tối ưu hóa Script. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.1
                                <small>Ngày 24 tháng 4 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm loại thanh toán đơn vị tiền tệ.</li>
                                <li> Đã thêm khả năng cho quản trị nhóm để xóa bài đăng của người dùng.</li>
                                <li> Đã thêm ngôn ngữ Bồ Đào Nha.</li>
                                <li> Đã thêm 2 thể loại thiết kế mới vào bảng quản trị ở đầu, (đầu trang nhập văn bản, bóng văn bản nút).</li>
                                <li> Đã thêm gửi nút tới trường bình luận. (Trên điện thoại) </li>
                                <li> Đã sửa lỗi chung.</li>
                                <li> Đã sửa lỗi bảo mật.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3
                                <small>Ngày 21 tháng 4 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống xác thực SMS (người dùng xác thực bằng số điện thoại).</li>
                                <li> Đã thêm thành viên cap cấp (Star - Hot - Utlima - Vip) cùng PayPal / tích hợp thẻ tín dụng.</li>
                                <li> Đã thêm ứng dụng Android, IOS, and Windows Phone (web-view).</li>
                                <li> Đã thêm tính năng định vị lại bìa.</li>
                                <li> Đã thêm sự kiện sinh nhật ở trang chủ.</li>
                                <li> Đã thêm khả năng tăng bài đăng và thanh toán hàng tháng.</li>
                                <li> Đã thêm giới hạn bài đăng mỗi giờ cho mỗi người dùng.</li>
                                <li> Đã thêm giới hạn đăng ký mỗi giờ cho mỗi IP.</li>
                                <li> Đã thêm tùy chỉnh tập tin CSS cho mỗi người dùng (người dùng có thể thiết kế lại thông tin của mình)</li>
                                <li> Đã thêm Video.JS/Audio.JS cho video & người nghe.</li>
                                <li> Đã thêm tốc độ mới cho tất cả hành động, (Theo dõi, thêm bạn bè, trò chuyện, thích, không thích, vui, tham gia etc ..).</li>
                                <li> Đã thêm thông báo máy tính để Google Chrome / FireFox.</li>
                                <li> Đã thêm khả năng tải lên video .mov, .flv, .mpeg Videos.</li>
                                <li> Tạo dự án CSRF cho mẫu chung.</li>
                                <li> Đã thêm cấp bậc người dùng, quản trị viên - người kiểm duyệt - người dùng.</li>
                                <li> Đã thêm gửi nút để tin nhắn.</li>
                                <li> Đã thêm thanh người dùng nổi bật (đăng ký bằng thanh toán).</li>
                                <li> Đã thêm danh sách người dùng hoạt động ở bảng quản trị.</li>
                                <li> Đã thêm hệ thống mời.</li>
                                <li> Đã thêm gắn thẻ og-Meta cho chia sẻ xã hội.</li>
                                <li> Đã thêm hệ thống tải mới (tải nội dung mà không cần tải lại trang) và hệ thống tiết kiệm băng thông.</li>
                                <li> Đã thêm hệ thống thông báo E-mail mới.</li>
                                <li> Đã thêm hệ thống chặn.</li>
                                <li> Đã thêm nguồn mới để ứng dụng hỗ trợ.</li>
                                <li> Tối ưu hóa bố cụ.</li>
                                <li> Tăng tốc SMTP.</li>
                                <li> Hệ thống thay thế bộ nhớ.</li>
                                <li> Loại bỏ/chào mừng từ trang chào mừng URL.</li>
                                <li> Cập nhật API với v1.3.</li>
                                <li> Tối ưu hóa Script & code.</li>
                                <li> Tối ưu hóa SEO.</li>
                                <li> Cải thiện việc sử dụng tài nguyên của hệ thống trò chuyện.</li>
                                <li> Tăng bảo mật trang (XSS, CSRF, SQL, Spams).</li>
                                <li> Sửa quốc gia mặc định (USA).</li>
                                <li> Sửa lỗi chung.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.3
                                <small>Ngày 26 tháng 2 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm máy chủ SMTP.<br>
                                <li> Đã thêm đăng nhập cùng với tên tài khoản hoặc email.</li>
                                <li> Đã thêm phiên bản xây dựng ở bảng quản trị.</li>
                                <li> Sửa lỗi lớn.</li>
                                <li> Bảo mật đã được cải thiện.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.2
                                <small>Ngày 29 tháng 1 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm gợi ý đề cập tự động trong hộp nhà xuất bản, bình luận, phản hồi. </li>
                                <li> Đã thêm bắt đầu trang (Đã thêm ảnh, điền thông tin, người theo dõi).</li>
                                <li> Đã thêm điều khoản trang vào bảng quản trị. (Quản trị viên có thể chỉnh sửa điều khoản trang từ bảng quản trị).</li>
                                <li> Đã thêm cài đặt cập nhật video, audio vào bảng quản trị.</li>
                                <li> Đã thêm người thay đổi nền ảnh chào mừng vào bảng quản trị.</li>
                                <li> Đã thêm màu thiết kế trang để thông báo email.</li>
                                <li> Đã thêm chính sách bảo mật người dùng cho người dùng không đăng nhập.</li>
                                <li> Đã thêm nút cười để bình luận, gửi tin nhắn.</li>
                                <li> Đã thêm người cài đặt để cài đặt dễ dàng.</li>
                                <li> Gỡ lỗi từ phản hồi của bạn.</li>
                                <li> Tối ưu hóa Script.</li>
                                <li> Tốc độ đã được cải thiện.</li>
                                <li> Bảo mật đã được cải thiện.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.1
                                <small>Ngày 12 tháng 1 năm 2016</small></h6>
                            <ul>
                                <li> Đã thêm từ vui, không thích, thích ở nút hành động bài viết.</li>
                                <li> Đã thêm khả năng chỉ thích hoặc không thích. (không thể chọn cả hai).</li>
                                <li> Đã thêm cảm xúc ô bài đăng. </li>
                                <li> Tối ưu hóa yêu cầu trò chuyện.</li>
                                <li> Gỡ lỗi từ phản hồi của bạn.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2
                                <small>Ngày 10 tháng 1 2016</small></h6>
                            <ul>
                                <li> Đã thêm hệ thống nhóm</li>
                                <li> Đã thêm hệ thống ứng dụng hỗ trợ</li>
                                <li> Đã thêm nút không thích</li>
                                <li> Đã thêm ô mới</li>
                                <li> Đã thêm đăng nhập trên Instagram</li>
                                <li> Đã thêm hệ thống yêu cầu xác thực</li>
                                <li> Đã thêm hệ thống tập ảnh</li>
                                <li> Đã thêm tải lên nhiều ảnh</li>
                                <li> Đã thêm hệ thống tự động tải cho bài viết</li>
                                <li> Đã thêm hệ thống tìm kiếm mới</li>
                                <li> Đã thêm tìm kiếm gần đây</li>
                                <li> Đã thêm hệ thống trang lời mời</li>
                                <li> Đã thêm hệ thống mời nhóm</li>
                                <li> Đã thêm hệ thống cấm IP</li>
                                <li> Đã xem cảm xúc/xem/chơi/nghe trạng thái bài đăng</li>
                                <li> Đã thêm hệ thống gọi hành động cho các trang</li>
                                <li> Đã thêm bộ đếm người dùng trực tuyến trên trang quản trị và trang chủ</li>
                                <li> Đã thêm tự động hoàn thành cài đặt vị trí cho người dùng/trang</li>
                                <li> Đã thêm hệ thống thiết kế (Tùy chỉnh phong cách và màu sắc trang web của bạn một cách dễ dàng từ bảng quản trị)</li>
                                <li> Đã thêm tìm kiếm gần đây</li>
                                <li> Đã thêm thông báo Popup</li>
                                <li> Đã thêm thông tin chính sách bảo mật người truy cập</li>
                                <li> Đã thêm chính sách bảo mật lần xem cuối</li>
                                <li> Đã thêm thông tin chính sách bảo mật ngày sinh</li>
                                <li> Đã thêm trình dò tự động cho video Youtube, Dailymotion, Vine, Vimeo, Facebook và liên kết soundcloud.</li>
                                <li> Đã thêm hỗ trợ https</li>
                                <li> Đã thêm hệ thống phản hồi bình luận</li>
                                <li> Đã thêm trình tự phát hiện bình luận</li>
                                <li> Đã thêm giáo dục vào thông tin người dùng</li>
                                <li> Đã thêm  khả năng thích/không thích/thắc mắc/bình luận trên ảnh đại diện và ảnh nền của người dùng.</li>
                                <li> Đã thêm cài đặt thông báo email</li>
                                <li> Đã thêm biểu đồ thống kê trang web trong bảng quản trị</li>
                                <li> Đã thêm địa chỉ IP để quản lý trang người dùng</li>
                                <li> Đã thêm ngôn ngữ mới (Italian)</li>
                                <li> Bỏ "@" từ địa chỉ thông tin người dùng</li>
                                <li> Bỏ "p/" từ địa chỉ trang</li>
                                <li> Bỏ "/home" từ địa chỉ trang chủ</li>
                                <li> Thay dổi toàn bộ bố cục bảng điều khiển quản trị viên</li>
                                <li> Thay đổi toàn bộ bố cục cài đặt người dùng/trang/nhóm</li>
                                <li> Cải thiện cửa sổ bật lên của người dùng</li>
                                <li> Cải thiện bố cục</li>
                                <li> Cải thiện bố cục trên điện thoại</li>
                                <li> Cải thiện hệ thống trò chuyện</li>
                                <li> Cải thiện trang bảo mật</li>
                                <li> Cải thiện liên kết xem trước</li>
                                <li> Cải thiện hệ thống bộ nhớ đệm lên mức cao hơn</li>
                                <li> Phiên bản API đã cập nhật lên v1.1</li>
                                <li> Tối ưu hóa Script</li>
                                <li> Gỡ lỗi </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.1
                                <small>Ngày 8 tháng 12 năm 2015</small></h6>
                            <ul>
                                <li> Hệ thống trang đã được thêm.</li>
                                <li> Xem trước liên kết đã được thêm.</li>
                                <li> Hệ thống loại người dùng và hệ thống "đã xem" tin nhắn đã được thêm.</li>
                                <li> Thông tin trường tùy chỉnh đã được thêm (Việc làm, Công ty, Mối quan hệ, Vị trí .. etc).</li>
                                <li> Thông tin vị trí bản đồ đã được thêm.</li>
                                <li> Thông tin ảnh đại diện đã được thêm. (người dùng có thể chọn ảnh đại diện của họ).</li>
                                <li> Video Facebook, Vimeo, Dailymotion đã được thêm.</li>
                                <li> Đã thêm người dùng chi tiết khi nhấn chuột vào liên kết người dùng.</li>
                                <li> Hệ thống từ bị kiểm duyệt đã được thêm.</li>
                                <li> 4 ngôn ngữ mới đã được thêm (Hà Lan, Đức, Tây Ban Nha, Pháp).</li>
                                <li> Hệ thống tìm kiếm bài đăng đã được thêm.</li>
                                <li> Thông báo hỗ trợ HTML đã được thêm.</li>
                                <li> Trang chào mừng đã thay đổi.</li>
                                <li> Kiểu thanh bên đã thay đổi.</li>
                                <li> Bố cục và Phong cách được cải thiện.</li>
                                <li> Bố cục trên điện thoại được cải thiện.</li>
                                <li> Bố cục bảng quản trị viên đã cải thiện.</li>
                                <li> Nhiều tính năng để gửi E-mail đến tất cả người dùng đã được thêm.</li>
                                <li> Tối ưu hóa Script.</li>
                                <li> Gỡ lỗi.</li>
                                <li> Cải thiện bảo mật.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.0 <small></small> </h6>
                            Phiên bản 1.0 được phát hành ngày 26 tháng 11 năm 2015.
                        </div>
                    </div>
                </div>
            </div>
        </div>
