<?php

$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 50;
$link = '';

if (!empty($filter_keyword)) {
    $link .= '&query=' . $filter_keyword;
    $sql = "(`post_id` LIKE '%$filter_keyword%' OR `postText` LIKE '%$filter_keyword%')";
    $posts = $db->where($sql);
}
if (!empty($_GET['range']) && in_array($_GET['range'], array('Today', 'Yesterday', 'This Week', 'This Month', 'Last Month', 'This Year'))) {
    if ($_GET['range'] == 'Today' || $_GET['range'] == 'Yesterday') {
        $this_start = strtotime(date('M') . " " . date('d') . ", " . date('Y') . " 12:00am");
        $this_end = strtotime(date('M') . " " . date('d') . ", " . date('Y') . " 11:59pm");
        if ($_GET['range'] == 'Yesterday') {
            $this_start = strtotime(date('M') . " " . date('d', strtotime("-1 days")) . ", " . date('Y') . " 12:00am");
            $this_end = strtotime(date('M') . " " . date('d', strtotime("-1 days")) . ", " . date('Y') . " 11:59pm");
        }
        $main_range = 'Today';
        $title = "Daily";
    } elseif ($_GET['range'] == 'This Week') {
        $time = strtotime(date('l') . ", " . date('M') . " " . date('d') . ", " . date('Y'));

        if (date('l') == 'Saturday') {
            $this_start = strtotime(date('M') . " " . date('d') . ", " . date('Y') . " 12:00am");
        } else {
            $this_start = strtotime('last saturday, 12:00am', $time);
        }

        if (date('l') == 'Friday') {
            $this_end = strtotime(date('M') . " " . date('d') . ", " . date('Y') . " 11:59pm");
        } else {
            $this_end = strtotime('next Friday, 11:59pm', $time);
        }

        $main_range = 'This Week';
        $title = "Weekly";
    } elseif ($_GET['range'] == 'This Month' || $_GET['range'] == 'Last Month') {
        $this_start = strtotime("1 " . date('M') . " " . date('Y') . " 12:00am");
        $this_end = strtotime(cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')) . " " . date('M') . " " . date('Y') . " 11:59pm");
        if ($_GET['range'] == 'Last Month') {
            $this_start = strtotime("1 " . date('M', strtotime("-1 month")) . " " . date('Y') . " 12:00am");
            $this_end = strtotime(cal_days_in_month(CAL_GREGORIAN, date('m', strtotime("-1 month")), date('Y')) . " " . date('M', strtotime("-1 month")) . " " . date('Y') . " 11:59pm");
        }
        $main_range = 'This Month';
        $title = "Monthly";
    } elseif ($_GET['range'] == 'This Year') {
        $this_start = strtotime("1 January " . date('Y') . " 12:00am");
        $this_end = strtotime("31 December " . date('Y') . " 11:59pm");
        $main_range = 'This Year';
        $title = "Yearly";
    }
}
$start = '';
$end = '';
$first_code = '';
$second_code = '';
if (!empty($_GET['range']) && !in_array($_GET['range'], array('Today', 'Yesterday', 'This Week', 'This Month', 'Last Month', 'This Year'))) {
    $arr = explode('-', $_GET['range']);
    if (preg_match('~(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d~m', $arr[0]) && preg_match('~(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d~m', $arr[1])) {
        $start = Wo_Secure($arr[0]);
        $end = Wo_Secure($arr[1]);
        $this_start = strtotime($start);
        $this_end = strtotime($end);
        $month_days = cal_days_in_month(CAL_GREGORIAN, date('m', strtotime($start)), date('Y', strtotime($start)));
        $diff = abs(strtotime($end) - strtotime($start));
        $years = floor($diff / (365 * 60 * 60 * 24));
        $months = floor(($diff - $years * 365 * 60 * 60 * 24) / (30 * 60 * 60 * 24));
        $days = floor(($diff - $years * 365 * 60 * 60 * 24 - $months * 30 * 60 * 60 * 24) / (60 * 60 * 24));
        if ($years >= 1) {
            $array = array();
            for ($i = date('Y', strtotime($start)); $i <= date('Y', strtotime($end)); $i++) {
                $array["'" . $i . "'"] = 0;
            }
            $main_range = 'Custom';
            $code = 'Y';
            $title = "Yearly";
        } elseif ($months >= 1) {
            $array = array('01' => 0, '02' => 0, '03' => 0, '04' => 0, '05' => 0, '06' => 0, '07' => 0, '08' => 0, '09' => 0, '10' => 0, '11' => 0, '12' => 0);
            $code = 'm';
            $main_range = 'This Year';
            $title = "Monthly";
            if (date('Y', strtotime($start)) == date('Y', strtotime($end))) {
                $array = array();
                for ($i = date('m', strtotime($start)); $i <= date('m', strtotime($end)); $i++) {
                    $array["'" . (int)$i . "'"] = 0;
                }
                $code = 'm';
                $main_range = 'Custom';
            } else {
                $month = cal_days_in_month(CAL_GREGORIAN, date('m', strtotime($start)), date('Y', strtotime($start)));
                $array = array();
                for ($i = (int)date('m', strtotime($start)); $i <= 12; $i++) {
                    $array["'" . (int)$i . '-' . date('Y', strtotime($start)) . "'"] = 0;
                }
                for ($i = 1; $i <= (int)date('m', strtotime($end)); $i++) {
                    $array["'" . (int)$i . '-' . date('Y', strtotime($end)) . "'"] = 0;
                }
                $first_code = 'm';
                $second_code = 'Y';
                $main_range = 'Custom';
            }
        } elseif ($days > 7) {
            if (date('m', strtotime($start)) == date('m', strtotime($end))) {
                $array = array();
                for ($i = date('d', strtotime($start)); $i <= date('d', strtotime($end)); $i++) {
                    $array["'" . (int)$i . "'"] = 0;
                }
                $code = 'd';
                $main_range = 'Custom';
            } else {
                $month = cal_days_in_month(CAL_GREGORIAN, date('m', strtotime($start)), date('Y', strtotime($start)));
                $array = array();
                for ($i = (int)date('d', strtotime($start)); $i <= $month; $i++) {
                    $array["'" . (int)$i . '-' . date('m', strtotime($start)) . "'"] = 0;
                }
                for ($i = 1; $i <= (int)date('d', strtotime($end)); $i++) {
                    $array["'" . (int)$i . '-' . date('m', strtotime($end)) . "'"] = 0;
                }
                $first_code = 'd';
                $second_code = 'm';
                $main_range = 'Custom';
            }
            $title = "Daily";
        } elseif ($days >= 1 && $days < 8) {
            $title = "Daily";
            $code = 'l';
            $array = array('Saturday' => 0, 'Sunday' => 0, 'Monday' => 0, 'Tuesday' => 0, 'Wednesday' => 0, 'Thursday' => 0, 'Friday' => 0);
            if (date('m', strtotime($start)) == date('m', strtotime($end))) {
                $array = array();
                for ($i = date('d', strtotime($start)); $i <= date('d', strtotime($end)); $i++) {
                    $array["'" . (int)$i . "'"] = 0;
                }
                $code = 'd';
                $main_range = 'Custom';
            } else {
                $month = cal_days_in_month(CAL_GREGORIAN, date('m', strtotime($start)), date('Y', strtotime($start)));
                $array = array();
                for ($i = (int)date('d', strtotime($start)); $i <= $month; $i++) {
                    $array["'" . (int)$i . '-' . date('m', strtotime($start)) . "'"] = 0;
                }
                for ($i = 1; $i <= (int)date('d', strtotime($end)); $i++) {
                    $array["'" . (int)$i . '-' . date('m', strtotime($end)) . "'"] = 0;
                }
                $first_code = 'd';
                $second_code = 'm';
                $main_range = 'Custom';
            }
        }
    }
}


$rang_link = $link;
if (!empty($this_start) && !empty($this_end)) {
    $link .= "&range=" . Wo_Secure($_GET['range']);
    $db->where('time', $this_start, '>=')->where('time', $this_end, '<=');
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('id', 'DESC'),
    'ASC_i' => array('id', 'ASC'),
    'DESC_t' => array('time', 'DESC'),
    'ASC_t' => array('time', 'ASC'),
    'DESC_a' => array('active', 'DESC'),
    'ASC_a' => array('active', 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $link .= "&sort=" . Wo_Secure($_GET['sort']);
    $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
} else {
    $_GET['sort'] = 'DESC_i';
    $db->orderBy('id', 'DESC');
}
$posts = $db->objectbuilder()->paginate(T_POSTS, $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-posts'));
    exit();
}

?>

<div class="container-fluid">
    <div>
        <h3>Bài đăng</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Quản lý tính năng</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Bài đăng</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng bình luận</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountAllData('comments'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng lượt thích</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-info-bright text-info rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPostData('likes'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng lượt không thích</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-warning-bright text-warning rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="M7.5 15h2.25m8.024-9.75c.011.05.028.1.052.148.591 1.2.924 2.55.924 3.977a8.96 8.96 0 01-.999 4.125m.023-8.25c-.076-.365.183-.75.575-.75h.908c.889 0 1.713.518 1.972 1.368.339 1.11.521 2.287.521 3.507 0 1.553-.295 3.036-.831 4.398C20.613 14.547 19.833 15 19 15h-1.053c-.472 0-.745-.556-.5-.96a8.95 8.95 0 00.303-.54m.023-8.25H16.48a4.5 4.5 0 01-1.423-.23l-3.114-1.04a4.5 4.5 0 00-1.423-.23H6.504c-.618 0-1.217.247-1.605.729A11.95 11.95 0 002.25 12c0 .434.023.863.068 1.285C2.427 14.306 3.346 15 4.372 15h3.126c.618 0 .991.724.725 1.282A7.471 7.471 0 007.5 19.5a2.25 2.25 0 002.25 2.25.75.75 0 00.75-.75v-.633c0-.573.11-1.14.322-1.672.304-.76.93-1.33 1.653-1.715a9.04 9.04 0 002.86-2.4c.498-.634 1.226-1.08 2.032-1.08h.384"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPostData('wonders'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng phản hồi</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPostData('replies'); ?></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <div id="dashboard-daterangepicker" class="btn btn-outline-light pull-right">
                        <?php
                        if (!empty($_GET['range']) && in_array($_GET['range'], array('Today', 'Yesterday', 'This Week', 'This Month', 'Last Month', 'This Year'))) {
                            echo $_GET['range'];
                        } else if (!empty($start) && !empty($end)) {
                            echo $_GET['range'];
                        } else {
                            echo 'All';
                        } ?>
                    </div>
                    <h6 class="card-title">Quản lý và chỉnh sửa bài đăng</h6>
                    <div class="row">
                        <div class="col-md-9" style="margin-bottom:0;">
                            <form method="get" action="<?php echo Wo_LoadAdminLinkSettings('manage-posts'); ?>">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label search-form">
                                                    Tìm kiếm mã bài đăng, văn bản bài đăng.
                                                </label>
                                                <input type="text" name="query" id="query" class="form-control"
                                                       value="<?php echo($filter_keyword); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <button class="btn btn-info">Tìm kiếm</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                        <div class="col-md-3" style="margin-bottom:0;">

                        </div>
                    </div>
                    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    <div class="clearfix"></div>
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="check-all" class="filled-in check-all"><label
                                            for="check-all"></label></th>
                                <th>ID
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_i') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=ASC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=DESC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Nhà xuất bản</th>
                                <th>Liên kết bài đăng</th>
                                <th>Đã đăng
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_t') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=ASC_t") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=DESC_t") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Trạng thái
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_a') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=ASC_a") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $sort_link . "&sort=DESC_a") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Hành động</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php
                            foreach ($posts as $post) {
                                $wo['story'] = $post;
                                if (!empty($post->user_id)) {
                                    $wo['story']->publisher = Wo_UserData($post->user_id);
                                } elseif (!empty($post->page_id)) {
                                    $user_page = Wo_PageData($post->page_id);
                                    $wo['story']->publisher = Wo_UserData($user_page['user_id']);
                                }
                                if ($wo['config']['useSeoFrindly'] == 1) {
                                    $wo['story']->url = Wo_SeoLink('index.php?link1=post&id=' . $post->id) . '_' . Wo_SlugPost($post->postText);
                                } else {
                                    $wo['story']->url = Wo_SeoLink('index.php?link1=post&id=' . $post->id);
                                }

                                echo Wo_LoadAdminPage('manage-posts/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                        <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=1') . $link; ?>"
                                           data-ajax="?path=manage-posts&page-id=1<?php echo($link); ?>"
                                           class="waves-effect" title='First Page'>
                                            <i class="material-icons">Trang đầu</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($page - 1)) . $link; ?>"
                                               data-ajax="?path=manage-posts&page-id=<?php echo($page - 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php } ?>

                                    <?php
                                    $nums = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($i)) . $link; ?>"
                                                   data-ajax="?path=manage-posts&page-id=<?php echo($i) ?><?php echo($link); ?>"
                                                   class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>

                                        <?php }
                                        $nums++;
                                    } ?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($page + 1)) . $link; ?>"
                                               data-ajax="?path=manage-posts&page-id=<?php echo($page + 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($db->totalPages)) . $link; ?>"
                                           data-ajax="?path=manage-posts&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                           class="waves-effect" title='Last Page'>
                                            <i class="material-icons">Trang cuối</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-2 col-md-2">
                                <span>Hành động</span>
                                <select class="form-control show-tick" id="action_type">
                                    <option value="activate">Kích hoạt</option>
                                    <option value="deactivate">Vô hiệu hóa</option>
                                    <option value="delete">Xóa</option>
                                </select>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block"
                                        disabled>Xác nhận<span></span></button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa bài đăng?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn chắc chắn muốn xóa bài đăng này?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Xóa</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xác nhận bài đăng?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn chắc chắn muốn xác nhận bài đăng này?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Xác nhận</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa bài đăng?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn chắc chắn rằng bạn muốn bỏ lựa chọn bài đăng?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">Xác
                        nhận
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script>
        jQuery(document).ready(function ($) {
            var range = {
                "All": [moment().startOf('year'), moment().endOf('year')],
                "Today": [moment(), moment()],
                "Yesterday": [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                "This_Week": [moment().subtract(6, 'days'), moment()],
                "This_Month": [moment().startOf('month'), moment().endOf('month')],
                "Last_Month": [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                "This_Year": [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')]
            };
            <?php
            if (!empty($_GET['range']) && in_array($_GET['range'], array('Today', 'Yesterday', 'This Week', 'This Month', 'Last Month', 'This Year'))) {
            if ($_GET['range'] == 'Today') { ?>
            var start = range.Today[0];
            var end = range.Today[1];
            <?php }elseif ($_GET['range'] == 'Yesterday') { ?>
            var start = range.Yesterday[0];
            var end = range.Yesterday[1];
            <?php }elseif ($_GET['range'] == 'This Week') { ?>
            var start = range.This_Week[0];
            var end = range.This_Week[1];
            <?php }elseif ($_GET['range'] == 'This Month') { ?>
            var start = range.This_Month[0];
            var end = range.This_Month[1];
            <?php }elseif ($_GET['range'] == 'Last Month') { ?>
            var start = range.Last_Month[0];
            var end = range.Last_Month[1];
            <?php }elseif ($_GET['range'] == 'This Year') { ?>
            var start = range.This_Year[0];
            var end = range.This_Year[1];
            <?php } ?>
            <?php } elseif (!empty($_GET['range']) && !empty($start) && !empty($end)) { ?>
            var start = "<?php echo($start) ?>";
            var end = "<?php echo($end) ?>";
            <?php } else{ ?>
            var start = range.All[0];
            var end = range.All[1];
            <?php } ?>

            function cb(start, end) {
                //$('#dashboard-daterangepicker span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            }

            $('#dashboard-daterangepicker').daterangepicker({
                startDate: start,
                endDate: end,
                opens: $('body').hasClass('rtl') ? 'right' : 'left',
                ranges: {
                    'All': [moment().startOf('year'), moment().endOf('year')],
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'This Week': [moment().subtract(6, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                    'This Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')],
                }
            }, cb);


            cb(start, end);

            // setTimeout(function (argument) {
            //     $('.ranges ul li').removeClass('active');
            // },800);

            $(document).on('click', '.ranges ul li', function (event) {
                event.preventDefault();
                if ($(this).attr('data-range-key') != 'Custom Range') {
                    $(document).off('click', '.ranges ul li');
                    $('#redirect_link').attr('href', "<?php echo Wo_LoadAdminLinkSettings('manage-posts') . $rang_link; ?>&range=" + $(this).attr('data-range-key'));
                    $('#redirect_link').attr('data-ajax', "?path=manage-posts<?php echo('&' . $rang_link) ?>&range=" + $(this).attr('data-range-key'));
                    $('#redirect_link').click();
                    //location.href = "<?php echo Wo_LoadAdminLinkSettings('manage-posts') . $rang_link; ?>&range="+$(this).attr('data-range-key');
                }
            });
            $(document).on('click', '.applyBtn', function (event) {
                event.preventDefault();
                $(document).off('click', '.applyBtn');
                $('#redirect_link').attr('href', "<?php echo Wo_LoadAdminLinkSettings('manage-posts') . $rang_link; ?>&range=" + $(this).parent('.drp-buttons').find('.drp-selected').html());
                $('#redirect_link').attr('data-ajax', "?path=manage-posts<?php echo('&' . $rang_link) ?>&range=" + $(this).parent('.drp-buttons').find('.drp-selected').html());
                $('#redirect_link').click();
                //location.href = "<?php echo Wo_LoadAdminLinkSettings('manage-posts') . $rang_link; ?>&range="+$('.drp-selected').html();
            });
        });


        $('.check-all').on('click', function (event) {
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
        $('.delete-checkbox, .check-all').change(function (event) {
            $('.delete-selected').attr('disabled', false);
            $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
        });
        $('.delete-selected').on('click', function (event) {
            event.preventDefault();
            action_type = $('#action_type').val();
            $('#SelectedDeleteModal').find('.modal-body').html('Are you sure that you want to ' + action_type + ' the selected post(s)?');
            $('#SelectedDeleteModal').find('#exampleModal1Label').html(action_type + ' post(s)');
            $('#SelectedDeleteModal').modal('show');
        });

        function DeleteSelected() {
            action_type = $('#action_type').val();
            data = new Array();
            $('td input:checked').parents('tr').each(function () {
                data.push($(this).attr('data_selected'));
            });
            $('.delete-selected').attr('disabled', true);
            $('.delete-selected').text('Please wait..');
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_multi_post', {
                ids: data,
                type: action_type
            }, function () {
                if (action_type == 'delete') {
                    $.each(data, function (index, value) {
                        $('#PostID_' + value).remove();
                    });
                } else {
                    location.reload();
                }
                $('.delete-selected').text('Submit');
            });
        }

        function Wo_AdminDeletePost(post_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_AdminDeletePost('" + post_id + "')");
                $('#DeleteModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PostID_' + post_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_post', {post_id: post_id, hash_id: hash_id});
        }

        function Wo_AdminApprovePost(post_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal2').find('.btn-primary').attr('onclick', "Wo_AdminApprovePost('" + post_id + "')");
                $('#DeleteModal2').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=approve_post', {
                post_id: post_id,
                hash_id: hash_id
            }, function (data, textStatus, xhr) {
                location.reload();
            });
        }

    </script>