<div class="container-fluid">
    <div>
        <h3>Tự động xóa dữ liệu trang web</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Công cụ</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Tự động xóa dữ liệu trang web</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                  <h6 class="card-title">Tự động xóa dữ liệu trang web</h6>
                    <div class="alert alert-info">Bạn nên tạo bản sao trước khi áp dụng bất kỳ hành động nào.</div>
                   <label for="delete">Chọn nội dung bạn muốn xóa</label>
                        <select class="form-control show-tick" id="delete" name="delete">
                           <option value="1">Xóa tất cả người dùng không hoạt động</option>
                           <option value="2">Xóa những người dùng không đăng nhập hơn 1 tuần</option>
                           <option value="3">Xóa những người dùng không đăng nhập hơn 1 tháng</option>
                           <option value="4">Xóa những người dùng không đăng nhập hơn 1 năm</option>
                           <option value="5">Xóa những bài đăng thời gian dài hơn 1 tuần</option>
                           <option value="6">Xóa những bài đăng thời gian dài hơn 1 tháng</option>
                           <option value="7">Xóa những bài đăng thời gian dài hơn 1 năm</option>
                        </select>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="alert alert-warning">Quá trình này có thể mất một thời gian, bạn có thể kiểm tra những thay đổi trên trang sau ít phút.</div>
                        <div class="clearfix"></div>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="delete-btn" onclick="Wo_DeleteAuto('hide');">Xóa dữ liệu</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal1Label">Xóa tự động?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
               Bạn có chắc chắn muốn xóa? Hành động này không thể hoàn tác.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Xóa</button>
            </div>
        </div>
    </div>
</div>
<script>
  function Wo_DeleteAuto(type = 'show') {
  if (type == 'hide') {
      $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeleteAuto()");
      $('#DeleteModal').modal('show');
      return false;
    }
    $('#delete-btn').text('Please wait..');
  $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_delete', delete: $('#delete').val()}, function(data, textStatus, xhr) {
    $('#delete-btn').text('Data is being deleted, check your site after few mins.');
    setTimeout(function () {
      $('#delete-btn').text('Delete Data');
    }, 4000);
  });
}
</script>