<div class="container-fluid">
    <div>
        <h3>Cài đặt E-mail & SMS</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Cài đặt</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Cài đặt E-mail & SMS</li>
            </ol>
        </nav>
    </div>
    <div class="alert alert-info">
       <i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Thông tin: </strong> Để biết thêm thông tin về cách thiết lập máy chủ e-mail hoặc nhà cung cấp SMS, hãy ghé trang <a href="https://docs.wowonder.com/#idocs_smtp" target="_blank">Tài liệu</a> trang.
   </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cấu hình E-mail</h6>
                    <form class="email-settings" method="POST">
                        <label for="smtp_or_mail" class="main-label">Máy chủ E-mail</label>
                        <select class="form-control show-tick" id="smtp_or_mail" name="smtp_or_mail">
                          <option value="smtp" <?php if($wo['config']['smtp_or_mail'] == 'smtp'){echo 'selected';};?> >Máy chủ SMTP</option>
                          <option value="mail" <?php if($wo['config']['smtp_or_mail'] == 'mail'){echo 'selected';};?> >Máy chủ Mail (Mặc định)</option>
                        </select>
                        <small class="admin-info">Chọn máy chủ E-mail bạn muốn sử dụng, chức năng máy chủ mail không được khuyến khích.</small>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mặc định trang web E-mail</label>
                                <input type="text" id="siteEmail" name="siteEmail" class="form-control" value="<?php echo $wo['config']['siteEmail']; ?>">
                                <small class="admin-info">Đây là trang web mặc định E-mail, nó sẽ được sử dụng để gửi E-mails đến người dùng.</small>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Chủ tài khoản SMTP</label>
                                <input type="text" id="smtp_host" name="smtp_host" class="form-control" value="<?php echo $wo['config']['smtp_host'];?>">
                                <small class="admin-info">Tên chủ tài khoản SMTP, có được IP, miền hoặc miền con.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên người dùng SMTP</label>
                                <input type="text" id="smtp_username" name="smtp_username" class="form-control" value="<?php echo $wo['config']['smtp_username'];?>">
                                <small class="admin-info">Tên tài khoản người dùng SMTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mật khẩu SMTP</label>
                                <input type="password" id="smtp_password" name="smtp_password" class="form-control" value="<?php echo openssl_decrypt($wo['config']['smtp_password'], "AES-128-ECB", 'mysecretkey1234');?>">
                                <small class="admin-info">Mật khẩu tài khoản SMTP của bạn.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Cổng SMTP</label>
                                <input type="text" id="smtp_port" name="smtp_port" class="form-control" value="<?php echo $wo['config']['smtp_port'];?>">
                                <small class="admin-info">Máy chủ SMTP của bạn sử dụng cổng nào? được sử dụng nhiều nhất 587 cho mã hóa TLS, và 465 cho mã hóa SSL. </small>
                            </div>
                        </div>
                        <label for="smtp_encryption">Mã hóa SMTP</label>
                        <select class="form-control show-tick" id="smtp_encryption" name="smtp_encryption">
                          <option value="tls" <?php if((strtolower($wo['config']['smtp_encryption']) == 'tls')){echo 'selected';};?> >TLS (Mặc định, không bảo mật)</option>
                          <option value="ssl" <?php if((strtolower($wo['config']['smtp_encryption']) == 'ssl')){echo 'selected';};?> >SSL (Bảo mật)</option>
                        </select>
                        <small class="admin-info">Phương thức mã hóa máy chủ SMTP của bạn sử dụng?</small>
                        <div class="clearfix"></div><br>
                        <div class="alert alert-info">
                            Sau khi nhấn "Kiểm tra máy chủ E-mail", tin nhắn kiểm tra sẽ được gửi đến địa chỉ tài khoản email của bạn.
                        </div>
                        <div class="email-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestMessage();">Kiểm tra máy chủ E-mail</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Cài đặt SMS</h6>

                    <form class="sms-settings" method="POST">
                        <div class="alert alert-info">Để bắt đầu gửi SMS, bạn phải tạo một tài khoản và mua tín dụng trong<a href="http://www.twilio.com">Twilio</a> <span class="red">OR</span> <a href="http://www.bulksms.com/">BulkSMS</a> <span class="red">hoặc</span> <a href="https://www.infobip.com/">Infobip</a>.</div><br>

                        <label for="sms_provider" class="main-label">Nhà cung cấp SMS mặc định</label>
                        <select class="form-control show-tick" id="sms_provider" name="sms_provider">
                          <option value="twilio" <?php if($wo['config']['sms_provider'] == 'twilio'){echo 'selected';};?> >Twilio</option>
                          <option value="bulksms" <?php if($wo['config']['sms_provider'] == 'bulksms'){echo 'selected';};?> >BulkSMS</option>
                          <option value="infobip" <?php if($wo['config']['sms_provider'] == 'infobip'){echo 'selected';};?> >Infobip</option>
                          <option value="msg91" <?php if($wo['config']['sms_provider'] == 'msg91'){echo 'selected';};?> >Msg91</option>
                        </select>
                        <small class="admin-info">Chọn nhà cung cấp bạn muốn sử dụng, bạn chỉ có thể sử dụng một nhà cung cấp ở một thời điểm.</small>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Số điện thoại của bạn</label>
                                <input type="text" id="sms_phone_number" name="sms_phone_number" class="form-control" value="<?php echo $wo['config']['sms_phone_number'];?>">
                                <small class="admin-info">Đặt số điện thoại mặc định cho trang web của bạn, nó sẽ được sử dụng để gửi SMS đến người dùng, ví dụ (+9053..)</small>
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">Cấu hình BulkSMS </label><br><br>
                        <!-- <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">BulkSMS Eapi_URL</label>
                                <input type="text" id="eapi" name="eapi" class="form-control" value="<?php echo $wo['config']['eapi'];?>">
                            </div>
                        </div> -->
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên tài khoản BulkSMS</label>
                                <input type="text" id="sms_username" name="sms_username" class="form-control" value="<?php echo $wo['config']['sms_username'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mật khẩu BulkSMS</label>
                                <input type="password" id="sms_password" name="sms_password" class="form-control" value="<?php echo $wo['config']['sms_password'];?>">
                            </div>
                        </div>
                       <hr>
                       <label  class="main-label">Cấu hình Twilio</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên tài khoản Twilio</label>
                                <input type="text" id="sms_twilio_username" name="sms_twilio_username" class="form-control" value="<?php echo $wo['config']['sms_twilio_username'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Mật khẩu Twilio</label>
                                <input type="text" id="sms_twilio_password" name="sms_twilio_password" class="form-control" value="<?php echo $wo['config']['sms_twilio_password'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Số điện thoại Twilio</label>
                                <input type="text" id="sms_t_phone_number" name="sms_t_phone_number" class="form-control" value="<?php echo $wo['config']['sms_t_phone_number'];?>">
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">Cấu hình Infobip</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa Infobip API</label>
                                <input type="text" id="infobip_api_key" name="infobip_api_key" class="form-control" value="<?php echo $wo['config']['infobip_api_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Liên kết cơ sở Infobip</label>
                                <input type="text" id="infobip_base_url" name="infobip_base_url" class="form-control" value="<?php echo $wo['config']['infobip_base_url'];?>">
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">Cấu hình Msg91</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Khóa xác thực Msg91</label>
                                <input type="text" id="msg91_authKey" name="msg91_authKey" class="form-control" value="<?php echo $wo['config']['msg91_authKey'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Msg91 DLT ID</label>
                                <input type="text" id="msg91_dlt_id" name="msg91_dlt_id" class="form-control" value="<?php echo $wo['config']['msg91_dlt_id'];?>">
                            </div>
                        </div>


                        <div class="alert alert-info">Sau khi ấn chọn "Kiểm tra máy chủ SMS", Một tin nhắn kiểm tra sẽ được gửi đến điện thoại của bạn</div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="sms-settings-alert"></div>
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestSMSMessage();">Kiểm tra máy chủ SMS</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Gỡ lỗi khả năng gửi Email</h6>
                    <div class="alert alert-info">Tính năng này sẽ kiểm tra khả năng gửi Email và chắc chắn rằng hệ thống đang làm việc tốt.</div>
                    <form class="debug-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Nhật ký gỡ lỗi</label>
                                <textarea name="debug_email" id="debug_email" class="form-control" cols="30" rows="5" style="height: 700px !important;" disabled>Nhấn chọn gỡ lỗi Email Deliverability để hiển thị kết quả kiểm tra.</textarea>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="debug-settings-alert"></div>
                        <button type="submit" class="btn btn-success m-t-15 waves-effect">Gỡ lỗi khả năng gửi Email</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
function Wo_TestMessage() {
    $('form.email-settings').find('.btn-success').text('Please wait..');
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_message'}, function (data) {
        if (data.status == 200) {
            $('.email-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Message sent!</div>');
            setTimeout(function () {
                $('.email-settings-alert').empty();
            }, 2000);
        } else {
            $('.email-settings-alert').html('<div class="alert alert-danger">Message failed to sent, error: ' + data.error+'</div>');
            setTimeout(function () {
                $('.email-settings-alert').empty();
            }, 2000);
        }
        $('form.email-settings').find('.btn-success').text('Test E-mail Server');
    });
}
function Wo_TestSMSMessage() {
    $('form.sms-settings').find('.btn-success').text('Please wait..');
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_sms_message'}, function (data) {
        if (data.status == 200) {
            $('.sms-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Message sent!</div>');
            setTimeout(function () {
                $('.sms-settings-alert').empty();
            }, 2000);
        } else {
            $('.sms-settings-alert').html('<div class="alert alert-danger">Message failed to sent, error: ' + data.error+'</div>');
            setTimeout(function () {
                $('.sms-settings-alert').empty();
            }, 2000);
        }
        $('form.sms-settings').find('.btn-success').text('Test SMS Server');
    });
}
$(function() {
    var debug_settings = $('form.debug-settings');
    debug_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=email_debug',
        beforeSend: function() {
            debug_settings.find('.waves-effect').text("Please wait..");
        },
        success: function(data) {
            debug_settings.find('.waves-effect').text('Debug');
            $('#debug_email').val(data);
        },
        error: function(data) {
            debug_settings.find('.waves-effect').text('Debug');
            $('#debug_email').val(data.responseText);
        }
    });

    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], input[type=password]').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
</script>
