<?php

$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 50;
$link = '';


if (!empty($filter_keyword)) {
    $link .= '&query=' . $filter_keyword;
    $sql = "(
    `page_id`          LIKE '%$filter_keyword%' OR 
    `page_name`        LIKE '%$filter_keyword%' OR
    `page_title`       LIKE '%$filter_keyword%' OR
    `page_description` LIKE '%$filter_keyword%'
  )";

    $pages = $db->where($sql);
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('page_id', 'DESC'),
    'ASC_i' => array('page_id', 'ASC'),
    'DESC_n' => array('page_title', 'DESC'),
    'ASC_n' => array('page_title', 'ASC'),
    'DESC_c' => array('page_category', 'DESC'),
    'ASC_c' => array('page_category', 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $link .= "&sort=" . Wo_Secure($_GET['sort']);
    $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
} else {
    $_GET['sort'] = 'DESC_i';
    $db->orderBy('page_id', 'DESC');
}
$pages = $db->objectbuilder()->paginate(T_PAGES, $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-pages'));
    exit();
}

?>

<div class="container-fluid">
    <div>
        <h3>Trang</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Quản lý tính năng</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Trang</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng trang</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                              d="M3 3v1.5M3 21v-6m0 0l2.77-.693a9 9 0 016.208.682l.108.054a9 9 0 006.086.71l3.114-.732a48.524 48.524 0 01-.005-10.499l-3.11.732a9 9 0 01-6.085-.711l-.108-.054a9 9 0 00-6.208-.682L3 4.5M3 15V4.5"/>
                                  </svg>

                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountAllData('page'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng lượt thích</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-info-bright text-info rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"/>
                                  </svg>

                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPageData('likes'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng bài đăng</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-warning-bright text-warning rounded-pill">
                                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                           stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                          <path stroke-linecap="round" stroke-linejoin="round"
                                                d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"/>
                                      </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPageData('pages_posts'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Trang xác thực</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountPageData('verified_pages'); ?></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Quản lý và chỉnh sửa trang</h6>
                    <div class="row">
                        <div class="col-md-4" style="margin-bottom:0;">
                            <form method="get" action="<?php echo Wo_LoadAdminLinkSettings('manage-pages'); ?>">
                                <div class="row">
                                    <div class="col-md-11">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label search-form">
                                                    Tìm kiếm mã trang, tên trang, tiêu đề trang.
                                                </label>
                                                <input type="text" name="query" id="query" class="form-control"
                                                       value="<?php echo($filter_keyword); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <button class="btn btn-info">Tìm kiếm</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    <div class="clearfix"></div>
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="check-all" class="filled-in check-all"><label
                                            for="check-all"></label></th>
                                <th>ID
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_i') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=ASC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=DESC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Tên trang
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_n') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=ASC_n") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=DESC_n") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Người sở hữu</th>
                                <th>Danh mục
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_c') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=ASC_c") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $sort_link . "&sort=DESC_c") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Hành động</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($pages as $pagelist) {
                                $wo['pagelist'] = Wo_PageData($pagelist->page_id);
                                $wo['pagelist']['owner'] = Wo_UserData($pagelist->user_id);
                                echo Wo_LoadAdminPage('manage-pages/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                        <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-pages?page-id=1') . $link; ?>"
                                           data-ajax="?path=manage-pages&page-id=1<?php echo($link); ?>"
                                           class="waves-effect" title='First Page'>
                                            <i class="material-icons">Trang đầu</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-pages?page-id=' . ($page - 1)) . $link; ?>"
                                               data-ajax="?path=manage-pages&page-id=<?php echo($page - 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php } ?>

                                    <?php
                                    $nums = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-pages?page-id=' . ($i)) . $link; ?>"
                                                   data-ajax="?path=manage-pages&page-id=<?php echo($i) ?><?php echo($link); ?>"
                                                   class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>

                                        <?php }
                                        $nums++;
                                    } ?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-pages?page-id=' . ($page + 1)) . $link; ?>"
                                               data-ajax="?path=manage-pages&page-id=<?php echo($page + 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-pages?page-id=' . ($db->totalPages)) . $link; ?>"
                                           data-ajax="?path=manage-pages&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                           class="waves-effect" title='Last Page'>
                                            <i class="material-icons">Trang cuối</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block"
                                        disabled>Xóa lựa chọn<span></span></button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa trang?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn chắc chắn rằng bạn muốn bỏ trang đã chọn?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">Xác
                        nhận
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa trang?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn chắc chắn muốn xóa trang này?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Xóa</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('.check-all').on('click', function (event) {
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
        $('.delete-checkbox, .check-all').change(function (event) {
            $('.delete-selected').attr('disabled', false);
            $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
        });

        $('.delete-selected').on('click', function (event) {
            event.preventDefault();
            $('#SelectedDeleteModal').modal('show');
        });

        function DeleteSelected() {
            data = new Array();
            $('td input:checked').parents('tr').each(function () {
                data.push($(this).attr('data_selected'));
            });
            $('.delete-selected').attr('disabled', true);
            $('.delete-selected').text('Please wait..');
            $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_multi_page", {ids: data}, function () {
                $.each(data, function (index, value) {
                    $("#PageID_" + value).remove();
                });
                $('.delete-selected').text('Delete Selected');
            });
        }

        function Wo_DeletePage(page_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeletePage('" + page_id + "')");
                $('#DeleteModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#PageID_' + page_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_user_page',
                page_id: page_id,
                hash_id: hash_id
            });
        }

    </script>