<?php
$page = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type = '';
$db->pageLimit = 50;
$link = '';

if (!empty($filter_keyword)) {
    $link .= '&query=' . $filter_keyword;
    $sql = "(
    `id`          LIKE '%$filter_keyword%' OR 
    `group_name`  LIKE '%$filter_keyword%' OR
    `group_title` LIKE '%$filter_keyword%' OR
    `about`       LIKE '%$filter_keyword%'
  )";

    $db->where($sql);
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('id', 'DESC'),
    'ASC_i' => array('id', 'ASC'),
    'DESC_n' => array('group_name', 'DESC'),
    'ASC_n' => array('group_name', 'ASC'),
    'DESC_c' => array('category', 'DESC'),
    'ASC_c' => array('category', 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $link .= "&sort=" . Wo_Secure($_GET['sort']);
    $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
} else {
    $_GET['sort'] = 'DESC_i';
    $db->orderBy('id', 'DESC');
}
$groups = $db->objectbuilder()->paginate(T_GROUPS, $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-groups'));
    exit();
}

?>
<div class="container-fluid">
    <div>
        <h3>Nhóm</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Quản lý tính năng</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Nhóm</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng nhóm</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountAllData('group'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tham gia nhóm</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-info-bright text-info rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountGroupData('members'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tổng bài đăng</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-warning-bright text-warning rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"/>
                                  </svg>

                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountGroupData('groups_posts'); ?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Yêu cầu tham gia</h6>
                    <div class="d-flex align-items-center mb-3">
                        <div>
                            <div class="avatar">
                              <span class="avatar-title bg-primary-bright text-primary rounded-pill">
                                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                       stroke-width="1.5" stroke="currentColor" width="24px" height="24px">
                                      <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"/>
                                  </svg>
                              </span>
                            </div>
                        </div>
                        <div class="font-weight-bold ml-1 font-size-30 ml-3"><?php echo Wo_CountGroupData('join_requests'); ?></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Quản lý và chỉnh sửa nhóm</h6>
                    <div class="row">
                        <div class="col-md-4" style="margin-bottom:0;">
                            <form method="get" action="<?php echo Wo_LoadAdminLinkSettings('manage-groups'); ?>">
                                <div class="row">
                                    <div class="col-md-11">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label search-form">
                                                    Tìm kiếm mã nhóm, tên nhóm, tiêu đề nhóm.
                                                </label>
                                                <input type="text" name="query" id="query" class="form-control"
                                                       value="<?php echo($filter_keyword); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <button class="btn btn-info">Tìm kiếm</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                    <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    <div class="clearfix"></div>
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="check-all" class="filled-in check-all"><label
                                            for="check-all"></label></th>
                                <th>ID
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_i') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=ASC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=DESC_i") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Tên nhóm
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_n') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=ASC_n") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=DESC_n") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Người sở hữu</th>
                                <th>Danh mục
                                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_c') { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=ASC_c") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-up cursor-p">
                                            <line x1="12" y1="19" x2="12" y2="5"></line>
                                            <polyline points="5 12 12 5 19 12"></polyline>
                                        </svg>
                                    <?php } else { ?>
                                        <svg onclick="location.href = '<?php echo(Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $sort_link . "&sort=DESC_c") ?>'"
                                             xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="feather feather-arrow-down cursor-p">
                                            <line x1="12" y1="5" x2="12" y2="19"></line>
                                            <polyline points="19 12 12 19 5 12"></polyline>
                                        </svg>
                                    <?php } ?></th>
                                <th>Thành viên</th>
                                <th>Hành động</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($groups as $grouplist) {
                                $wo['grouplist'] = Wo_GroupData($grouplist->id);
                                $wo['grouplist']['members'] = Wo_CountGroupMembers($grouplist->id);
                                $wo['grouplist']['owner'] = Wo_UserData($grouplist->user_id);
                                echo Wo_LoadAdminPage('manage-groups/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="wo-admincp-feturepager">
                        <div class="pull-left">
                            <span>
                              <?php echo "Showing $page out of " . $db->totalPages; ?>
                            </span>
                        </div>
                        <div class="pull-right">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=1') . $link; ?>"
                                           data-ajax="?path=manage-groups&page-id=1<?php echo($link); ?>"
                                           class="waves-effect" title='First Page'>
                                            <i class="material-icons">Trang đầu</i>
                                        </a>
                                    </li>
                                    <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($page - 1)) . $link; ?>"
                                               data-ajax="?path=manage-groups&page-id=<?php echo($page - 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                    <?php } ?>

                                    <?php
                                    $nums = 0;
                                    $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                    for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                        if ($nums < 20) {
                                            ?>
                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($i)) . $link; ?>"
                                                   data-ajax="?path=manage-groups&page-id=<?php echo($i) ?><?php echo($link); ?>"
                                                   class="waves-effect">
                                                    <?php echo $i ?>
                                                </a>
                                            </li>

                                        <?php }
                                        $nums++;
                                    } ?>

                                    <?php if ($db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($page + 1)) . $link; ?>"
                                               data-ajax="?path=manage-groups&page-id=<?php echo($page + 1) ?><?php echo($link); ?>"
                                               class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                    <?php } ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-groups?page-id=' . ($db->totalPages)) . $link; ?>"
                                           data-ajax="?path=manage-groups&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                           class="waves-effect" title='Last Page'>
                                            <i class="material-icons">Trang cuối</i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block"
                                        disabled>Xóa lựa chọn<span></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa nhóm?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn có chắc chắn rằng muốn bỏ nhóm đã chọn?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">Xác
                        nhận
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal1Label">Xóa nhóm?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Bạn có chắc chắn muốn xóa nhóm này?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Xóa</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('.check-all').on('click', function (event) {
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
        $('.delete-checkbox, .check-all').change(function (event) {
            $('.delete-selected').attr('disabled', false);
            $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
        });

        $('.delete-selected').on('click', function (event) {
            event.preventDefault();
            $('#SelectedDeleteModal').modal('show');
        });

        function DeleteSelected() {
            data = new Array();
            $('td input:checked').parents('tr').each(function () {
                data.push($(this).attr('data_selected'));
            });
            $('.delete-selected').attr('disabled', true);
            $('.delete-selected').text('Please wait..');
            $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_multi_group", {ids: data}, function () {
                $.each(data, function (index, value) {
                    $("#GroupID_" + value).remove();
                });
                $('.delete-selected').text('Delete Selected');
            });
        }

        function Wo_DeleteGroup(group_id, type = 'show') {
            if (type == 'hide') {
                $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeleteGroup('" + group_id + "')");
                $('#DeleteModal').modal('show');
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#GroupID_' + group_id).fadeOut(300, function () {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(), {
                f: 'admin_setting',
                s: 'delete_group',
                group_id: group_id,
                hash_id: hash_id
            });
        }

    </script>