<div class="container-fluid">
    <div>
        <h3>Tự động thích trang</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Trang chủ</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Công cụ</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Tự động thích trang</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Tự động thích trang</h6>
                    <div class="alert alert-info">Khi người dùng tạo một tài khoản mới, chọn trang mà bạn muốn tự động thích.</div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Tên trang</label>
                                <input type="text" id="users" name="users" class="form-control" value="<?php echo $wo['config']['auto_page_like']; ?>">
                            </div>
                        </div>
                        <hr>
                        <div class="clearfix"></div>
                        <div class="alert alert-warning">Quá trình này có thể mất một thời gian, bạn có thể kiểm tra lại sự thay đổi trang web sau một ít phút.</div>
                        <div class="clearfix"></div>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="users-btn-like">Lưu</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<script>
$(document).on('click', '#users-btn-like', function(event) {
	event.preventDefault();
	$(this).text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_page_like', users: $('#users').val()}, function(data, textStatus, xhr) {
		$('#users-btn-like').text('Saved!');
		setTimeout(function () {
			$('#users-btn-like').text('Save');
		}, 4000);
	});
});
</script>